package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyCustfina;
import com.org.fourfly.model.FourflyCustfinaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyCustfinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int insert(FourflyCustfina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int insertSelective(FourflyCustfina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    List<FourflyCustfina> selectByExample(FourflyCustfinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    FourflyCustfina selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyCustfina record, @Param("example") FourflyCustfinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyCustfina record, @Param("example") FourflyCustfinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyCustfina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_custfina
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyCustfina record);
}