package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyMeet;
import com.org.fourfly.model.FourflyMeetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyMeetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int insert(FourflyMeet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int insertSelective(FourflyMeet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    List<FourflyMeet> selectByExample(FourflyMeetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    FourflyMeet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyMeet record, @Param("example") FourflyMeetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyMeet record, @Param("example") FourflyMeetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyMeet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_meet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyMeet record);
}