package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyFiles;
import com.org.fourfly.model.FourflyFilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int insert(FourflyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int insertSelective(FourflyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    List<FourflyFiles> selectByExample(FourflyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    FourflyFiles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyFiles record, @Param("example") FourflyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyFiles record, @Param("example") FourflyFilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_files
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyFiles record);
}