package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyKqjuser;
import com.org.fourfly.model.FourflyKqjuserExample;
import com.org.fourfly.model.FourflyKqjuserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyKqjuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int insert(FourflyKqjuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int insertSelective(FourflyKqjuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    List<FourflyKqjuserWithBLOBs> selectByExampleWithBLOBs(FourflyKqjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    List<FourflyKqjuser> selectByExample(FourflyKqjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    FourflyKqjuserWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyKqjuserWithBLOBs record, @Param("example") FourflyKqjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FourflyKqjuserWithBLOBs record, @Param("example") FourflyKqjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyKqjuser record, @Param("example") FourflyKqjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyKqjuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FourflyKqjuserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyKqjuser record);
}