package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyCarmang;
import com.org.fourfly.model.FourflyCarmangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyCarmangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int insert(FourflyCarmang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int insertSelective(FourflyCarmang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    List<FourflyCarmang> selectByExample(FourflyCarmangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    FourflyCarmang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyCarmang record, @Param("example") FourflyCarmangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyCarmang record, @Param("example") FourflyCarmangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyCarmang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_carmang
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyCarmang record);
}