package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyFlowSet;
import com.org.fourfly.model.FourflyFlowSetExample;
import com.org.fourfly.model.FourflyFlowSetKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyFlowSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FourflyFlowSetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int insert(FourflyFlowSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int insertSelective(FourflyFlowSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    List<FourflyFlowSet> selectByExample(FourflyFlowSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    FourflyFlowSet selectByPrimaryKey(FourflyFlowSetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyFlowSet record, @Param("example") FourflyFlowSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyFlowSet record, @Param("example") FourflyFlowSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyFlowSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyFlowSet record);
}