package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyGoods;
import com.org.fourfly.model.FourflyGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int insert(FourflyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int insertSelective(FourflyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    List<FourflyGoods> selectByExample(FourflyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    FourflyGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyGoods record, @Param("example") FourflyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyGoods record, @Param("example") FourflyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyGoods record);
}