package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyKqjsn;
import com.org.fourfly.model.FourflyKqjsnExample;
import com.org.fourfly.model.FourflyKqjsnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyKqjsnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FourflyKqjsnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int insert(FourflyKqjsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int insertSelective(FourflyKqjsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    List<FourflyKqjsn> selectByExampleWithBLOBs(FourflyKqjsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    List<FourflyKqjsn> selectByExample(FourflyKqjsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    FourflyKqjsn selectByPrimaryKey(FourflyKqjsnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyKqjsn record, @Param("example") FourflyKqjsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FourflyKqjsn record, @Param("example") FourflyKqjsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyKqjsn record, @Param("example") FourflyKqjsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyKqjsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FourflyKqjsn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_kqjsn
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyKqjsn record);
}