package com.org.fourfly.mapper;

import com.org.fourfly.model.FourflyImMess;
import com.org.fourfly.model.FourflyImMessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FourflyImMessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int insert(FourflyImMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int insertSelective(FourflyImMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    List<FourflyImMess> selectByExample(FourflyImMessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    FourflyImMess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FourflyImMess record, @Param("example") FourflyImMessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FourflyImMess record, @Param("example") FourflyImMessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FourflyImMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_im_mess
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FourflyImMess record);
}