package com.org.fourfly.model;

import java.util.Date;

public class FourflyHrtransfer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.uid
     *
     * @mbg.generated
     */
    private Short uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.optid
     *
     * @mbg.generated
     */
    private Short optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.applydt
     *
     * @mbg.generated
     */
    private Date applydt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.isturn
     *
     * @mbg.generated
     */
    private Boolean isturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.tranuid
     *
     * @mbg.generated
     */
    private Short tranuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.tranname
     *
     * @mbg.generated
     */
    private String tranname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.trantype
     *
     * @mbg.generated
     */
    private String trantype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.olddeptname
     *
     * @mbg.generated
     */
    private String olddeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.oldranking
     *
     * @mbg.generated
     */
    private String oldranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.effectivedt
     *
     * @mbg.generated
     */
    private Date effectivedt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.newdeptname
     *
     * @mbg.generated
     */
    private String newdeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.newdeptid
     *
     * @mbg.generated
     */
    private Short newdeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.newranking
     *
     * @mbg.generated
     */
    private String newranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.isover
     *
     * @mbg.generated
     */
    private Boolean isover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrtransfer.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.id
     *
     * @return the value of fourfly_hrtransfer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.id
     *
     * @param id the value for fourfly_hrtransfer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.uid
     *
     * @return the value of fourfly_hrtransfer.uid
     *
     * @mbg.generated
     */
    public Short getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.uid
     *
     * @param uid the value for fourfly_hrtransfer.uid
     *
     * @mbg.generated
     */
    public void setUid(Short uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.optdt
     *
     * @return the value of fourfly_hrtransfer.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.optdt
     *
     * @param optdt the value for fourfly_hrtransfer.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.optid
     *
     * @return the value of fourfly_hrtransfer.optid
     *
     * @mbg.generated
     */
    public Short getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.optid
     *
     * @param optid the value for fourfly_hrtransfer.optid
     *
     * @mbg.generated
     */
    public void setOptid(Short optid) {
        this.optid = optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.optname
     *
     * @return the value of fourfly_hrtransfer.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.optname
     *
     * @param optname the value for fourfly_hrtransfer.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.applydt
     *
     * @return the value of fourfly_hrtransfer.applydt
     *
     * @mbg.generated
     */
    public Date getApplydt() {
        return applydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.applydt
     *
     * @param applydt the value for fourfly_hrtransfer.applydt
     *
     * @mbg.generated
     */
    public void setApplydt(Date applydt) {
        this.applydt = applydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.explain
     *
     * @return the value of fourfly_hrtransfer.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.explain
     *
     * @param explain the value for fourfly_hrtransfer.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.status
     *
     * @return the value of fourfly_hrtransfer.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.status
     *
     * @param status the value for fourfly_hrtransfer.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.isturn
     *
     * @return the value of fourfly_hrtransfer.isturn
     *
     * @mbg.generated
     */
    public Boolean getIsturn() {
        return isturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.isturn
     *
     * @param isturn the value for fourfly_hrtransfer.isturn
     *
     * @mbg.generated
     */
    public void setIsturn(Boolean isturn) {
        this.isturn = isturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.tranuid
     *
     * @return the value of fourfly_hrtransfer.tranuid
     *
     * @mbg.generated
     */
    public Short getTranuid() {
        return tranuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.tranuid
     *
     * @param tranuid the value for fourfly_hrtransfer.tranuid
     *
     * @mbg.generated
     */
    public void setTranuid(Short tranuid) {
        this.tranuid = tranuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.tranname
     *
     * @return the value of fourfly_hrtransfer.tranname
     *
     * @mbg.generated
     */
    public String getTranname() {
        return tranname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.tranname
     *
     * @param tranname the value for fourfly_hrtransfer.tranname
     *
     * @mbg.generated
     */
    public void setTranname(String tranname) {
        this.tranname = tranname == null ? null : tranname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.trantype
     *
     * @return the value of fourfly_hrtransfer.trantype
     *
     * @mbg.generated
     */
    public String getTrantype() {
        return trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.trantype
     *
     * @param trantype the value for fourfly_hrtransfer.trantype
     *
     * @mbg.generated
     */
    public void setTrantype(String trantype) {
        this.trantype = trantype == null ? null : trantype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.olddeptname
     *
     * @return the value of fourfly_hrtransfer.olddeptname
     *
     * @mbg.generated
     */
    public String getOlddeptname() {
        return olddeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.olddeptname
     *
     * @param olddeptname the value for fourfly_hrtransfer.olddeptname
     *
     * @mbg.generated
     */
    public void setOlddeptname(String olddeptname) {
        this.olddeptname = olddeptname == null ? null : olddeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.oldranking
     *
     * @return the value of fourfly_hrtransfer.oldranking
     *
     * @mbg.generated
     */
    public String getOldranking() {
        return oldranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.oldranking
     *
     * @param oldranking the value for fourfly_hrtransfer.oldranking
     *
     * @mbg.generated
     */
    public void setOldranking(String oldranking) {
        this.oldranking = oldranking == null ? null : oldranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.effectivedt
     *
     * @return the value of fourfly_hrtransfer.effectivedt
     *
     * @mbg.generated
     */
    public Date getEffectivedt() {
        return effectivedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.effectivedt
     *
     * @param effectivedt the value for fourfly_hrtransfer.effectivedt
     *
     * @mbg.generated
     */
    public void setEffectivedt(Date effectivedt) {
        this.effectivedt = effectivedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.newdeptname
     *
     * @return the value of fourfly_hrtransfer.newdeptname
     *
     * @mbg.generated
     */
    public String getNewdeptname() {
        return newdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.newdeptname
     *
     * @param newdeptname the value for fourfly_hrtransfer.newdeptname
     *
     * @mbg.generated
     */
    public void setNewdeptname(String newdeptname) {
        this.newdeptname = newdeptname == null ? null : newdeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.newdeptid
     *
     * @return the value of fourfly_hrtransfer.newdeptid
     *
     * @mbg.generated
     */
    public Short getNewdeptid() {
        return newdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.newdeptid
     *
     * @param newdeptid the value for fourfly_hrtransfer.newdeptid
     *
     * @mbg.generated
     */
    public void setNewdeptid(Short newdeptid) {
        this.newdeptid = newdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.newranking
     *
     * @return the value of fourfly_hrtransfer.newranking
     *
     * @mbg.generated
     */
    public String getNewranking() {
        return newranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.newranking
     *
     * @param newranking the value for fourfly_hrtransfer.newranking
     *
     * @mbg.generated
     */
    public void setNewranking(String newranking) {
        this.newranking = newranking == null ? null : newranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.isover
     *
     * @return the value of fourfly_hrtransfer.isover
     *
     * @mbg.generated
     */
    public Boolean getIsover() {
        return isover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.isover
     *
     * @param isover the value for fourfly_hrtransfer.isover
     *
     * @mbg.generated
     */
    public void setIsover(Boolean isover) {
        this.isover = isover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrtransfer.comid
     *
     * @return the value of fourfly_hrtransfer.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrtransfer.comid
     *
     * @param comid the value for fourfly_hrtransfer.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}