package com.org.fourfly.model;

public class FourflyImMesszt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_im_messzt.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_im_messzt.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_im_messzt.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_im_messzt.gid
     *
     * @mbg.generated
     */
    private Short gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_im_messzt.id
     *
     * @return the value of fourfly_im_messzt.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_im_messzt.id
     *
     * @param id the value for fourfly_im_messzt.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_im_messzt.mid
     *
     * @return the value of fourfly_im_messzt.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_im_messzt.mid
     *
     * @param mid the value for fourfly_im_messzt.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_im_messzt.uid
     *
     * @return the value of fourfly_im_messzt.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_im_messzt.uid
     *
     * @param uid the value for fourfly_im_messzt.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_im_messzt.gid
     *
     * @return the value of fourfly_im_messzt.gid
     *
     * @mbg.generated
     */
    public Short getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_im_messzt.gid
     *
     * @param gid the value for fourfly_im_messzt.gid
     *
     * @mbg.generated
     */
    public void setGid(Short gid) {
        this.gid = gid;
    }
}