package com.org.fourfly.model;

import java.math.BigDecimal;

public class FourflyGoodn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.mid
     *
     * @mbg.generated
     */
    private Short mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.aid
     *
     * @mbg.generated
     */
    private Short aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.count
     *
     * @mbg.generated
     */
    private Short count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.couns
     *
     * @mbg.generated
     */
    private Short couns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_goodn.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.id
     *
     * @return the value of fourfly_goodn.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.id
     *
     * @param id the value for fourfly_goodn.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.mid
     *
     * @return the value of fourfly_goodn.mid
     *
     * @mbg.generated
     */
    public Short getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.mid
     *
     * @param mid the value for fourfly_goodn.mid
     *
     * @mbg.generated
     */
    public void setMid(Short mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.aid
     *
     * @return the value of fourfly_goodn.aid
     *
     * @mbg.generated
     */
    public Short getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.aid
     *
     * @param aid the value for fourfly_goodn.aid
     *
     * @mbg.generated
     */
    public void setAid(Short aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.count
     *
     * @return the value of fourfly_goodn.count
     *
     * @mbg.generated
     */
    public Short getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.count
     *
     * @param count the value for fourfly_goodn.count
     *
     * @mbg.generated
     */
    public void setCount(Short count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.couns
     *
     * @return the value of fourfly_goodn.couns
     *
     * @mbg.generated
     */
    public Short getCouns() {
        return couns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.couns
     *
     * @param couns the value for fourfly_goodn.couns
     *
     * @mbg.generated
     */
    public void setCouns(Short couns) {
        this.couns = couns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.sort
     *
     * @return the value of fourfly_goodn.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.sort
     *
     * @param sort the value for fourfly_goodn.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.unit
     *
     * @return the value of fourfly_goodn.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.unit
     *
     * @param unit the value for fourfly_goodn.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.price
     *
     * @return the value of fourfly_goodn.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.price
     *
     * @param price the value for fourfly_goodn.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_goodn.comid
     *
     * @return the value of fourfly_goodn.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_goodn.comid
     *
     * @param comid the value for fourfly_goodn.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}