package com.org.fourfly.model;

public class FourflyFlowElement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.mid
     *
     * @mbg.generated
     */
    private Short mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.fields
     *
     * @mbg.generated
     */
    private String fields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.fieldstype
     *
     * @mbg.generated
     */
    private String fieldstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.dev
     *
     * @mbg.generated
     */
    private String dev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.isbt
     *
     * @mbg.generated
     */
    private Boolean isbt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.islu
     *
     * @mbg.generated
     */
    private Boolean islu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.iszs
     *
     * @mbg.generated
     */
    private Boolean iszs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.attr
     *
     * @mbg.generated
     */
    private String attr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.iszb
     *
     * @mbg.generated
     */
    private Boolean iszb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.isss
     *
     * @mbg.generated
     */
    private Boolean isss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.lattr
     *
     * @mbg.generated
     */
    private String lattr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.width
     *
     * @mbg.generated
     */
    private String width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.lens
     *
     * @mbg.generated
     */
    private Short lens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.savewhere
     *
     * @mbg.generated
     */
    private String savewhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.islb
     *
     * @mbg.generated
     */
    private Boolean islb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.ispx
     *
     * @mbg.generated
     */
    private Boolean ispx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.isalign
     *
     * @mbg.generated
     */
    private Boolean isalign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.issou
     *
     * @mbg.generated
     */
    private Boolean issou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.istj
     *
     * @mbg.generated
     */
    private Boolean istj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.gongsi
     *
     * @mbg.generated
     */
    private String gongsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.placeholder
     *
     * @mbg.generated
     */
    private String placeholder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.isonly
     *
     * @mbg.generated
     */
    private Boolean isonly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_element.isdr
     *
     * @mbg.generated
     */
    private Boolean isdr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.id
     *
     * @return the value of fourfly_flow_element.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.id
     *
     * @param id the value for fourfly_flow_element.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.mid
     *
     * @return the value of fourfly_flow_element.mid
     *
     * @mbg.generated
     */
    public Short getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.mid
     *
     * @param mid the value for fourfly_flow_element.mid
     *
     * @mbg.generated
     */
    public void setMid(Short mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.name
     *
     * @return the value of fourfly_flow_element.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.name
     *
     * @param name the value for fourfly_flow_element.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.fields
     *
     * @return the value of fourfly_flow_element.fields
     *
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.fields
     *
     * @param fields the value for fourfly_flow_element.fields
     *
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.fieldstype
     *
     * @return the value of fourfly_flow_element.fieldstype
     *
     * @mbg.generated
     */
    public String getFieldstype() {
        return fieldstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.fieldstype
     *
     * @param fieldstype the value for fourfly_flow_element.fieldstype
     *
     * @mbg.generated
     */
    public void setFieldstype(String fieldstype) {
        this.fieldstype = fieldstype == null ? null : fieldstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.sort
     *
     * @return the value of fourfly_flow_element.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.sort
     *
     * @param sort the value for fourfly_flow_element.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.dev
     *
     * @return the value of fourfly_flow_element.dev
     *
     * @mbg.generated
     */
    public String getDev() {
        return dev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.dev
     *
     * @param dev the value for fourfly_flow_element.dev
     *
     * @mbg.generated
     */
    public void setDev(String dev) {
        this.dev = dev == null ? null : dev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.isbt
     *
     * @return the value of fourfly_flow_element.isbt
     *
     * @mbg.generated
     */
    public Boolean getIsbt() {
        return isbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.isbt
     *
     * @param isbt the value for fourfly_flow_element.isbt
     *
     * @mbg.generated
     */
    public void setIsbt(Boolean isbt) {
        this.isbt = isbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.data
     *
     * @return the value of fourfly_flow_element.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.data
     *
     * @param data the value for fourfly_flow_element.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.islu
     *
     * @return the value of fourfly_flow_element.islu
     *
     * @mbg.generated
     */
    public Boolean getIslu() {
        return islu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.islu
     *
     * @param islu the value for fourfly_flow_element.islu
     *
     * @mbg.generated
     */
    public void setIslu(Boolean islu) {
        this.islu = islu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.iszs
     *
     * @return the value of fourfly_flow_element.iszs
     *
     * @mbg.generated
     */
    public Boolean getIszs() {
        return iszs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.iszs
     *
     * @param iszs the value for fourfly_flow_element.iszs
     *
     * @mbg.generated
     */
    public void setIszs(Boolean iszs) {
        this.iszs = iszs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.attr
     *
     * @return the value of fourfly_flow_element.attr
     *
     * @mbg.generated
     */
    public String getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.attr
     *
     * @param attr the value for fourfly_flow_element.attr
     *
     * @mbg.generated
     */
    public void setAttr(String attr) {
        this.attr = attr == null ? null : attr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.iszb
     *
     * @return the value of fourfly_flow_element.iszb
     *
     * @mbg.generated
     */
    public Boolean getIszb() {
        return iszb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.iszb
     *
     * @param iszb the value for fourfly_flow_element.iszb
     *
     * @mbg.generated
     */
    public void setIszb(Boolean iszb) {
        this.iszb = iszb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.isss
     *
     * @return the value of fourfly_flow_element.isss
     *
     * @mbg.generated
     */
    public Boolean getIsss() {
        return isss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.isss
     *
     * @param isss the value for fourfly_flow_element.isss
     *
     * @mbg.generated
     */
    public void setIsss(Boolean isss) {
        this.isss = isss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.lattr
     *
     * @return the value of fourfly_flow_element.lattr
     *
     * @mbg.generated
     */
    public String getLattr() {
        return lattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.lattr
     *
     * @param lattr the value for fourfly_flow_element.lattr
     *
     * @mbg.generated
     */
    public void setLattr(String lattr) {
        this.lattr = lattr == null ? null : lattr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.width
     *
     * @return the value of fourfly_flow_element.width
     *
     * @mbg.generated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.width
     *
     * @param width the value for fourfly_flow_element.width
     *
     * @mbg.generated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.lens
     *
     * @return the value of fourfly_flow_element.lens
     *
     * @mbg.generated
     */
    public Short getLens() {
        return lens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.lens
     *
     * @param lens the value for fourfly_flow_element.lens
     *
     * @mbg.generated
     */
    public void setLens(Short lens) {
        this.lens = lens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.savewhere
     *
     * @return the value of fourfly_flow_element.savewhere
     *
     * @mbg.generated
     */
    public String getSavewhere() {
        return savewhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.savewhere
     *
     * @param savewhere the value for fourfly_flow_element.savewhere
     *
     * @mbg.generated
     */
    public void setSavewhere(String savewhere) {
        this.savewhere = savewhere == null ? null : savewhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.islb
     *
     * @return the value of fourfly_flow_element.islb
     *
     * @mbg.generated
     */
    public Boolean getIslb() {
        return islb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.islb
     *
     * @param islb the value for fourfly_flow_element.islb
     *
     * @mbg.generated
     */
    public void setIslb(Boolean islb) {
        this.islb = islb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.ispx
     *
     * @return the value of fourfly_flow_element.ispx
     *
     * @mbg.generated
     */
    public Boolean getIspx() {
        return ispx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.ispx
     *
     * @param ispx the value for fourfly_flow_element.ispx
     *
     * @mbg.generated
     */
    public void setIspx(Boolean ispx) {
        this.ispx = ispx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.isalign
     *
     * @return the value of fourfly_flow_element.isalign
     *
     * @mbg.generated
     */
    public Boolean getIsalign() {
        return isalign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.isalign
     *
     * @param isalign the value for fourfly_flow_element.isalign
     *
     * @mbg.generated
     */
    public void setIsalign(Boolean isalign) {
        this.isalign = isalign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.issou
     *
     * @return the value of fourfly_flow_element.issou
     *
     * @mbg.generated
     */
    public Boolean getIssou() {
        return issou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.issou
     *
     * @param issou the value for fourfly_flow_element.issou
     *
     * @mbg.generated
     */
    public void setIssou(Boolean issou) {
        this.issou = issou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.istj
     *
     * @return the value of fourfly_flow_element.istj
     *
     * @mbg.generated
     */
    public Boolean getIstj() {
        return istj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.istj
     *
     * @param istj the value for fourfly_flow_element.istj
     *
     * @mbg.generated
     */
    public void setIstj(Boolean istj) {
        this.istj = istj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.gongsi
     *
     * @return the value of fourfly_flow_element.gongsi
     *
     * @mbg.generated
     */
    public String getGongsi() {
        return gongsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.gongsi
     *
     * @param gongsi the value for fourfly_flow_element.gongsi
     *
     * @mbg.generated
     */
    public void setGongsi(String gongsi) {
        this.gongsi = gongsi == null ? null : gongsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.placeholder
     *
     * @return the value of fourfly_flow_element.placeholder
     *
     * @mbg.generated
     */
    public String getPlaceholder() {
        return placeholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.placeholder
     *
     * @param placeholder the value for fourfly_flow_element.placeholder
     *
     * @mbg.generated
     */
    public void setPlaceholder(String placeholder) {
        this.placeholder = placeholder == null ? null : placeholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.isonly
     *
     * @return the value of fourfly_flow_element.isonly
     *
     * @mbg.generated
     */
    public Boolean getIsonly() {
        return isonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.isonly
     *
     * @param isonly the value for fourfly_flow_element.isonly
     *
     * @mbg.generated
     */
    public void setIsonly(Boolean isonly) {
        this.isonly = isonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_element.isdr
     *
     * @return the value of fourfly_flow_element.isdr
     *
     * @mbg.generated
     */
    public Boolean getIsdr() {
        return isdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_element.isdr
     *
     * @param isdr the value for fourfly_flow_element.isdr
     *
     * @mbg.generated
     */
    public void setIsdr(Boolean isdr) {
        this.isdr = isdr;
    }
}