package com.org.fourfly.model;

import java.util.Date;

public class FourflyCustappy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.uid
     *
     * @mbg.generated
     */
    private Short uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.optid
     *
     * @mbg.generated
     */
    private Short optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.applydt
     *
     * @mbg.generated
     */
    private Date applydt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.isturn
     *
     * @mbg.generated
     */
    private Boolean isturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.custid
     *
     * @mbg.generated
     */
    private Integer custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.custname
     *
     * @mbg.generated
     */
    private String custname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_custappy.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.id
     *
     * @return the value of fourfly_custappy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.id
     *
     * @param id the value for fourfly_custappy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.uid
     *
     * @return the value of fourfly_custappy.uid
     *
     * @mbg.generated
     */
    public Short getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.uid
     *
     * @param uid the value for fourfly_custappy.uid
     *
     * @mbg.generated
     */
    public void setUid(Short uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.optdt
     *
     * @return the value of fourfly_custappy.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.optdt
     *
     * @param optdt the value for fourfly_custappy.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.optid
     *
     * @return the value of fourfly_custappy.optid
     *
     * @mbg.generated
     */
    public Short getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.optid
     *
     * @param optid the value for fourfly_custappy.optid
     *
     * @mbg.generated
     */
    public void setOptid(Short optid) {
        this.optid = optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.optname
     *
     * @return the value of fourfly_custappy.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.optname
     *
     * @param optname the value for fourfly_custappy.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.applydt
     *
     * @return the value of fourfly_custappy.applydt
     *
     * @mbg.generated
     */
    public Date getApplydt() {
        return applydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.applydt
     *
     * @param applydt the value for fourfly_custappy.applydt
     *
     * @mbg.generated
     */
    public void setApplydt(Date applydt) {
        this.applydt = applydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.explain
     *
     * @return the value of fourfly_custappy.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.explain
     *
     * @param explain the value for fourfly_custappy.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.status
     *
     * @return the value of fourfly_custappy.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.status
     *
     * @param status the value for fourfly_custappy.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.isturn
     *
     * @return the value of fourfly_custappy.isturn
     *
     * @mbg.generated
     */
    public Boolean getIsturn() {
        return isturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.isturn
     *
     * @param isturn the value for fourfly_custappy.isturn
     *
     * @mbg.generated
     */
    public void setIsturn(Boolean isturn) {
        this.isturn = isturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.custid
     *
     * @return the value of fourfly_custappy.custid
     *
     * @mbg.generated
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.custid
     *
     * @param custid the value for fourfly_custappy.custid
     *
     * @mbg.generated
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.custname
     *
     * @return the value of fourfly_custappy.custname
     *
     * @mbg.generated
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.custname
     *
     * @param custname the value for fourfly_custappy.custname
     *
     * @mbg.generated
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_custappy.comid
     *
     * @return the value of fourfly_custappy.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_custappy.comid
     *
     * @param comid the value for fourfly_custappy.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}