package com.org.fourfly.model;

import java.util.Date;

public class FourflyReads {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.table
     *
     * @mbg.generated
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.optid
     *
     * @mbg.generated
     */
    private Short optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.web
     *
     * @mbg.generated
     */
    private String web;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.adddt
     *
     * @mbg.generated
     */
    private Date adddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_reads.stotal
     *
     * @mbg.generated
     */
    private Short stotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.id
     *
     * @return the value of fourfly_reads.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.id
     *
     * @param id the value for fourfly_reads.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.table
     *
     * @return the value of fourfly_reads.table
     *
     * @mbg.generated
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.table
     *
     * @param table the value for fourfly_reads.table
     *
     * @mbg.generated
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.mid
     *
     * @return the value of fourfly_reads.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.mid
     *
     * @param mid the value for fourfly_reads.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.optid
     *
     * @return the value of fourfly_reads.optid
     *
     * @mbg.generated
     */
    public Short getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.optid
     *
     * @param optid the value for fourfly_reads.optid
     *
     * @mbg.generated
     */
    public void setOptid(Short optid) {
        this.optid = optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.optdt
     *
     * @return the value of fourfly_reads.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.optdt
     *
     * @param optdt the value for fourfly_reads.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.ip
     *
     * @return the value of fourfly_reads.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.ip
     *
     * @param ip the value for fourfly_reads.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.web
     *
     * @return the value of fourfly_reads.web
     *
     * @mbg.generated
     */
    public String getWeb() {
        return web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.web
     *
     * @param web the value for fourfly_reads.web
     *
     * @mbg.generated
     */
    public void setWeb(String web) {
        this.web = web == null ? null : web.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.adddt
     *
     * @return the value of fourfly_reads.adddt
     *
     * @mbg.generated
     */
    public Date getAdddt() {
        return adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.adddt
     *
     * @param adddt the value for fourfly_reads.adddt
     *
     * @mbg.generated
     */
    public void setAdddt(Date adddt) {
        this.adddt = adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_reads.stotal
     *
     * @return the value of fourfly_reads.stotal
     *
     * @mbg.generated
     */
    public Short getStotal() {
        return stotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_reads.stotal
     *
     * @param stotal the value for fourfly_reads.stotal
     *
     * @mbg.generated
     */
    public void setStotal(Short stotal) {
        this.stotal = stotal;
    }
}