package com.org.fourfly.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FourflyEmailmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public FourflyEmailmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Short value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Short value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Short value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Short value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Short value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Short value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Short> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Short> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Short value1, Short value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Short value1, Short value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSendidIsNull() {
            addCriterion("sendid is null");
            return (Criteria) this;
        }

        public Criteria andSendidIsNotNull() {
            addCriterion("sendid is not null");
            return (Criteria) this;
        }

        public Criteria andSendidEqualTo(Short value) {
            addCriterion("sendid =", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidNotEqualTo(Short value) {
            addCriterion("sendid <>", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidGreaterThan(Short value) {
            addCriterion("sendid >", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidGreaterThanOrEqualTo(Short value) {
            addCriterion("sendid >=", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidLessThan(Short value) {
            addCriterion("sendid <", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidLessThanOrEqualTo(Short value) {
            addCriterion("sendid <=", value, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidIn(List<Short> values) {
            addCriterion("sendid in", values, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidNotIn(List<Short> values) {
            addCriterion("sendid not in", values, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidBetween(Short value1, Short value2) {
            addCriterion("sendid between", value1, value2, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendidNotBetween(Short value1, Short value2) {
            addCriterion("sendid not between", value1, value2, "sendid");
            return (Criteria) this;
        }

        public Criteria andSendnameIsNull() {
            addCriterion("sendname is null");
            return (Criteria) this;
        }

        public Criteria andSendnameIsNotNull() {
            addCriterion("sendname is not null");
            return (Criteria) this;
        }

        public Criteria andSendnameEqualTo(String value) {
            addCriterion("sendname =", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameNotEqualTo(String value) {
            addCriterion("sendname <>", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameGreaterThan(String value) {
            addCriterion("sendname >", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameGreaterThanOrEqualTo(String value) {
            addCriterion("sendname >=", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameLessThan(String value) {
            addCriterion("sendname <", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameLessThanOrEqualTo(String value) {
            addCriterion("sendname <=", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameLike(String value) {
            addCriterion("sendname like", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameNotLike(String value) {
            addCriterion("sendname not like", value, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameIn(List<String> values) {
            addCriterion("sendname in", values, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameNotIn(List<String> values) {
            addCriterion("sendname not in", values, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameBetween(String value1, String value2) {
            addCriterion("sendname between", value1, value2, "sendname");
            return (Criteria) this;
        }

        public Criteria andSendnameNotBetween(String value1, String value2) {
            addCriterion("sendname not between", value1, value2, "sendname");
            return (Criteria) this;
        }

        public Criteria andSenddtIsNull() {
            addCriterion("senddt is null");
            return (Criteria) this;
        }

        public Criteria andSenddtIsNotNull() {
            addCriterion("senddt is not null");
            return (Criteria) this;
        }

        public Criteria andSenddtEqualTo(Date value) {
            addCriterion("senddt =", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotEqualTo(Date value) {
            addCriterion("senddt <>", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtGreaterThan(Date value) {
            addCriterion("senddt >", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtGreaterThanOrEqualTo(Date value) {
            addCriterion("senddt >=", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtLessThan(Date value) {
            addCriterion("senddt <", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtLessThanOrEqualTo(Date value) {
            addCriterion("senddt <=", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtIn(List<Date> values) {
            addCriterion("senddt in", values, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotIn(List<Date> values) {
            addCriterion("senddt not in", values, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtBetween(Date value1, Date value2) {
            addCriterion("senddt between", value1, value2, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotBetween(Date value1, Date value2) {
            addCriterion("senddt not between", value1, value2, "senddt");
            return (Criteria) this;
        }

        public Criteria andReceidIsNull() {
            addCriterion("receid is null");
            return (Criteria) this;
        }

        public Criteria andReceidIsNotNull() {
            addCriterion("receid is not null");
            return (Criteria) this;
        }

        public Criteria andReceidEqualTo(String value) {
            addCriterion("receid =", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotEqualTo(String value) {
            addCriterion("receid <>", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThan(String value) {
            addCriterion("receid >", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThanOrEqualTo(String value) {
            addCriterion("receid >=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThan(String value) {
            addCriterion("receid <", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThanOrEqualTo(String value) {
            addCriterion("receid <=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLike(String value) {
            addCriterion("receid like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotLike(String value) {
            addCriterion("receid not like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidIn(List<String> values) {
            addCriterion("receid in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotIn(List<String> values) {
            addCriterion("receid not in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidBetween(String value1, String value2) {
            addCriterion("receid between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotBetween(String value1, String value2) {
            addCriterion("receid not between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNull() {
            addCriterion("recename is null");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNotNull() {
            addCriterion("recename is not null");
            return (Criteria) this;
        }

        public Criteria andRecenameEqualTo(String value) {
            addCriterion("recename =", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotEqualTo(String value) {
            addCriterion("recename <>", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThan(String value) {
            addCriterion("recename >", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThanOrEqualTo(String value) {
            addCriterion("recename >=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThan(String value) {
            addCriterion("recename <", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThanOrEqualTo(String value) {
            addCriterion("recename <=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLike(String value) {
            addCriterion("recename like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotLike(String value) {
            addCriterion("recename not like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameIn(List<String> values) {
            addCriterion("recename in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotIn(List<String> values) {
            addCriterion("recename not in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameBetween(String value1, String value2) {
            addCriterion("recename between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotBetween(String value1, String value2) {
            addCriterion("recename not between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andIsturnIsNull() {
            addCriterion("isturn is null");
            return (Criteria) this;
        }

        public Criteria andIsturnIsNotNull() {
            addCriterion("isturn is not null");
            return (Criteria) this;
        }

        public Criteria andIsturnEqualTo(Boolean value) {
            addCriterion("isturn =", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnNotEqualTo(Boolean value) {
            addCriterion("isturn <>", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnGreaterThan(Boolean value) {
            addCriterion("isturn >", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isturn >=", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnLessThan(Boolean value) {
            addCriterion("isturn <", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnLessThanOrEqualTo(Boolean value) {
            addCriterion("isturn <=", value, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnIn(List<Boolean> values) {
            addCriterion("isturn in", values, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnNotIn(List<Boolean> values) {
            addCriterion("isturn not in", values, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnBetween(Boolean value1, Boolean value2) {
            addCriterion("isturn between", value1, value2, "isturn");
            return (Criteria) this;
        }

        public Criteria andIsturnNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isturn not between", value1, value2, "isturn");
            return (Criteria) this;
        }

        public Criteria andHidIsNull() {
            addCriterion("hid is null");
            return (Criteria) this;
        }

        public Criteria andHidIsNotNull() {
            addCriterion("hid is not null");
            return (Criteria) this;
        }

        public Criteria andHidEqualTo(Short value) {
            addCriterion("hid =", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotEqualTo(Short value) {
            addCriterion("hid <>", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThan(Short value) {
            addCriterion("hid >", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThanOrEqualTo(Short value) {
            addCriterion("hid >=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThan(Short value) {
            addCriterion("hid <", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThanOrEqualTo(Short value) {
            addCriterion("hid <=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidIn(List<Short> values) {
            addCriterion("hid in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotIn(List<Short> values) {
            addCriterion("hid not in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidBetween(Short value1, Short value2) {
            addCriterion("hid between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotBetween(Short value1, Short value2) {
            addCriterion("hid not between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andIsfileIsNull() {
            addCriterion("isfile is null");
            return (Criteria) this;
        }

        public Criteria andIsfileIsNotNull() {
            addCriterion("isfile is not null");
            return (Criteria) this;
        }

        public Criteria andIsfileEqualTo(Boolean value) {
            addCriterion("isfile =", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileNotEqualTo(Boolean value) {
            addCriterion("isfile <>", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileGreaterThan(Boolean value) {
            addCriterion("isfile >", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isfile >=", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileLessThan(Boolean value) {
            addCriterion("isfile <", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileLessThanOrEqualTo(Boolean value) {
            addCriterion("isfile <=", value, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileIn(List<Boolean> values) {
            addCriterion("isfile in", values, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileNotIn(List<Boolean> values) {
            addCriterion("isfile not in", values, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileBetween(Boolean value1, Boolean value2) {
            addCriterion("isfile between", value1, value2, "isfile");
            return (Criteria) this;
        }

        public Criteria andIsfileNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isfile not between", value1, value2, "isfile");
            return (Criteria) this;
        }

        public Criteria andApplydtIsNull() {
            addCriterion("applydt is null");
            return (Criteria) this;
        }

        public Criteria andApplydtIsNotNull() {
            addCriterion("applydt is not null");
            return (Criteria) this;
        }

        public Criteria andApplydtEqualTo(Date value) {
            addCriterionForJDBCDate("applydt =", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtNotEqualTo(Date value) {
            addCriterionForJDBCDate("applydt <>", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtGreaterThan(Date value) {
            addCriterionForJDBCDate("applydt >", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("applydt >=", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtLessThan(Date value) {
            addCriterionForJDBCDate("applydt <", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("applydt <=", value, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtIn(List<Date> values) {
            addCriterionForJDBCDate("applydt in", values, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtNotIn(List<Date> values) {
            addCriterionForJDBCDate("applydt not in", values, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("applydt between", value1, value2, "applydt");
            return (Criteria) this;
        }

        public Criteria andApplydtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("applydt not between", value1, value2, "applydt");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("message_id is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("message_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("message_id =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("message_id <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("message_id >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("message_id >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("message_id <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("message_id <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String value) {
            addCriterion("message_id like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String value) {
            addCriterion("message_id not like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("message_id in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("message_id not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("message_id between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("message_id not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andFromemailIsNull() {
            addCriterion("fromemail is null");
            return (Criteria) this;
        }

        public Criteria andFromemailIsNotNull() {
            addCriterion("fromemail is not null");
            return (Criteria) this;
        }

        public Criteria andFromemailEqualTo(String value) {
            addCriterion("fromemail =", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailNotEqualTo(String value) {
            addCriterion("fromemail <>", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailGreaterThan(String value) {
            addCriterion("fromemail >", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailGreaterThanOrEqualTo(String value) {
            addCriterion("fromemail >=", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailLessThan(String value) {
            addCriterion("fromemail <", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailLessThanOrEqualTo(String value) {
            addCriterion("fromemail <=", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailLike(String value) {
            addCriterion("fromemail like", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailNotLike(String value) {
            addCriterion("fromemail not like", value, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailIn(List<String> values) {
            addCriterion("fromemail in", values, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailNotIn(List<String> values) {
            addCriterion("fromemail not in", values, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailBetween(String value1, String value2) {
            addCriterion("fromemail between", value1, value2, "fromemail");
            return (Criteria) this;
        }

        public Criteria andFromemailNotBetween(String value1, String value2) {
            addCriterion("fromemail not between", value1, value2, "fromemail");
            return (Criteria) this;
        }

        public Criteria andToemailIsNull() {
            addCriterion("toemail is null");
            return (Criteria) this;
        }

        public Criteria andToemailIsNotNull() {
            addCriterion("toemail is not null");
            return (Criteria) this;
        }

        public Criteria andToemailEqualTo(String value) {
            addCriterion("toemail =", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailNotEqualTo(String value) {
            addCriterion("toemail <>", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailGreaterThan(String value) {
            addCriterion("toemail >", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailGreaterThanOrEqualTo(String value) {
            addCriterion("toemail >=", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailLessThan(String value) {
            addCriterion("toemail <", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailLessThanOrEqualTo(String value) {
            addCriterion("toemail <=", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailLike(String value) {
            addCriterion("toemail like", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailNotLike(String value) {
            addCriterion("toemail not like", value, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailIn(List<String> values) {
            addCriterion("toemail in", values, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailNotIn(List<String> values) {
            addCriterion("toemail not in", values, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailBetween(String value1, String value2) {
            addCriterion("toemail between", value1, value2, "toemail");
            return (Criteria) this;
        }

        public Criteria andToemailNotBetween(String value1, String value2) {
            addCriterion("toemail not between", value1, value2, "toemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailIsNull() {
            addCriterion("reply_toemail is null");
            return (Criteria) this;
        }

        public Criteria andReplyToemailIsNotNull() {
            addCriterion("reply_toemail is not null");
            return (Criteria) this;
        }

        public Criteria andReplyToemailEqualTo(String value) {
            addCriterion("reply_toemail =", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailNotEqualTo(String value) {
            addCriterion("reply_toemail <>", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailGreaterThan(String value) {
            addCriterion("reply_toemail >", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailGreaterThanOrEqualTo(String value) {
            addCriterion("reply_toemail >=", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailLessThan(String value) {
            addCriterion("reply_toemail <", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailLessThanOrEqualTo(String value) {
            addCriterion("reply_toemail <=", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailLike(String value) {
            addCriterion("reply_toemail like", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailNotLike(String value) {
            addCriterion("reply_toemail not like", value, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailIn(List<String> values) {
            addCriterion("reply_toemail in", values, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailNotIn(List<String> values) {
            addCriterion("reply_toemail not in", values, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailBetween(String value1, String value2) {
            addCriterion("reply_toemail between", value1, value2, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andReplyToemailNotBetween(String value1, String value2) {
            addCriterion("reply_toemail not between", value1, value2, "replyToemail");
            return (Criteria) this;
        }

        public Criteria andCcemailIsNull() {
            addCriterion("ccemail is null");
            return (Criteria) this;
        }

        public Criteria andCcemailIsNotNull() {
            addCriterion("ccemail is not null");
            return (Criteria) this;
        }

        public Criteria andCcemailEqualTo(String value) {
            addCriterion("ccemail =", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotEqualTo(String value) {
            addCriterion("ccemail <>", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailGreaterThan(String value) {
            addCriterion("ccemail >", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailGreaterThanOrEqualTo(String value) {
            addCriterion("ccemail >=", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLessThan(String value) {
            addCriterion("ccemail <", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLessThanOrEqualTo(String value) {
            addCriterion("ccemail <=", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLike(String value) {
            addCriterion("ccemail like", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotLike(String value) {
            addCriterion("ccemail not like", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailIn(List<String> values) {
            addCriterion("ccemail in", values, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotIn(List<String> values) {
            addCriterion("ccemail not in", values, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailBetween(String value1, String value2) {
            addCriterion("ccemail between", value1, value2, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotBetween(String value1, String value2) {
            addCriterion("ccemail not between", value1, value2, "ccemail");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Integer value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Integer value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Integer value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Integer value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Integer value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Integer> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Integer> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Integer value1, Integer value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andCcnameIsNull() {
            addCriterion("ccname is null");
            return (Criteria) this;
        }

        public Criteria andCcnameIsNotNull() {
            addCriterion("ccname is not null");
            return (Criteria) this;
        }

        public Criteria andCcnameEqualTo(String value) {
            addCriterion("ccname =", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotEqualTo(String value) {
            addCriterion("ccname <>", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameGreaterThan(String value) {
            addCriterion("ccname >", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameGreaterThanOrEqualTo(String value) {
            addCriterion("ccname >=", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLessThan(String value) {
            addCriterion("ccname <", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLessThanOrEqualTo(String value) {
            addCriterion("ccname <=", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLike(String value) {
            addCriterion("ccname like", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotLike(String value) {
            addCriterion("ccname not like", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameIn(List<String> values) {
            addCriterion("ccname in", values, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotIn(List<String> values) {
            addCriterion("ccname not in", values, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameBetween(String value1, String value2) {
            addCriterion("ccname between", value1, value2, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotBetween(String value1, String value2) {
            addCriterion("ccname not between", value1, value2, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcidIsNull() {
            addCriterion("ccid is null");
            return (Criteria) this;
        }

        public Criteria andCcidIsNotNull() {
            addCriterion("ccid is not null");
            return (Criteria) this;
        }

        public Criteria andCcidEqualTo(String value) {
            addCriterion("ccid =", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidNotEqualTo(String value) {
            addCriterion("ccid <>", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidGreaterThan(String value) {
            addCriterion("ccid >", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidGreaterThanOrEqualTo(String value) {
            addCriterion("ccid >=", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidLessThan(String value) {
            addCriterion("ccid <", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidLessThanOrEqualTo(String value) {
            addCriterion("ccid <=", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidLike(String value) {
            addCriterion("ccid like", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidNotLike(String value) {
            addCriterion("ccid not like", value, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidIn(List<String> values) {
            addCriterion("ccid in", values, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidNotIn(List<String> values) {
            addCriterion("ccid not in", values, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidBetween(String value1, String value2) {
            addCriterion("ccid between", value1, value2, "ccid");
            return (Criteria) this;
        }

        public Criteria andCcidNotBetween(String value1, String value2) {
            addCriterion("ccid not between", value1, value2, "ccid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Boolean value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Boolean value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Boolean value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Boolean value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Boolean> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Boolean> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNull() {
            addCriterion("optdt is null");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNotNull() {
            addCriterion("optdt is not null");
            return (Criteria) this;
        }

        public Criteria andOptdtEqualTo(Date value) {
            addCriterion("optdt =", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotEqualTo(Date value) {
            addCriterion("optdt <>", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThan(Date value) {
            addCriterion("optdt >", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThanOrEqualTo(Date value) {
            addCriterion("optdt >=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThan(Date value) {
            addCriterion("optdt <", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThanOrEqualTo(Date value) {
            addCriterion("optdt <=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtIn(List<Date> values) {
            addCriterion("optdt in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotIn(List<Date> values) {
            addCriterion("optdt not in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtBetween(Date value1, Date value2) {
            addCriterion("optdt between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotBetween(Date value1, Date value2) {
            addCriterion("optdt not between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andNumoiIsNull() {
            addCriterion("numoi is null");
            return (Criteria) this;
        }

        public Criteria andNumoiIsNotNull() {
            addCriterion("numoi is not null");
            return (Criteria) this;
        }

        public Criteria andNumoiEqualTo(Integer value) {
            addCriterion("numoi =", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiNotEqualTo(Integer value) {
            addCriterion("numoi <>", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiGreaterThan(Integer value) {
            addCriterion("numoi >", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiGreaterThanOrEqualTo(Integer value) {
            addCriterion("numoi >=", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiLessThan(Integer value) {
            addCriterion("numoi <", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiLessThanOrEqualTo(Integer value) {
            addCriterion("numoi <=", value, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiIn(List<Integer> values) {
            addCriterion("numoi in", values, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiNotIn(List<Integer> values) {
            addCriterion("numoi not in", values, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiBetween(Integer value1, Integer value2) {
            addCriterion("numoi between", value1, value2, "numoi");
            return (Criteria) this;
        }

        public Criteria andNumoiNotBetween(Integer value1, Integer value2) {
            addCriterion("numoi not between", value1, value2, "numoi");
            return (Criteria) this;
        }

        public Criteria andComidIsNull() {
            addCriterion("comid is null");
            return (Criteria) this;
        }

        public Criteria andComidIsNotNull() {
            addCriterion("comid is not null");
            return (Criteria) this;
        }

        public Criteria andComidEqualTo(Short value) {
            addCriterion("comid =", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotEqualTo(Short value) {
            addCriterion("comid <>", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidGreaterThan(Short value) {
            addCriterion("comid >", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidGreaterThanOrEqualTo(Short value) {
            addCriterion("comid >=", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidLessThan(Short value) {
            addCriterion("comid <", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidLessThanOrEqualTo(Short value) {
            addCriterion("comid <=", value, "comid");
            return (Criteria) this;
        }

        public Criteria andComidIn(List<Short> values) {
            addCriterion("comid in", values, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotIn(List<Short> values) {
            addCriterion("comid not in", values, "comid");
            return (Criteria) this;
        }

        public Criteria andComidBetween(Short value1, Short value2) {
            addCriterion("comid between", value1, value2, "comid");
            return (Criteria) this;
        }

        public Criteria andComidNotBetween(Short value1, Short value2) {
            addCriterion("comid not between", value1, value2, "comid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_emailm
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_emailm
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}