package com.org.fourfly.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FourflyFlowCourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public FourflyFlowCourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andNidIsNull() {
            addCriterion("nid is null");
            return (Criteria) this;
        }

        public Criteria andNidIsNotNull() {
            addCriterion("nid is not null");
            return (Criteria) this;
        }

        public Criteria andNidEqualTo(Integer value) {
            addCriterion("nid =", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotEqualTo(Integer value) {
            addCriterion("nid <>", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThan(Integer value) {
            addCriterion("nid >", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThanOrEqualTo(Integer value) {
            addCriterion("nid >=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThan(Integer value) {
            addCriterion("nid <", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThanOrEqualTo(Integer value) {
            addCriterion("nid <=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidIn(List<Integer> values) {
            addCriterion("nid in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotIn(List<Integer> values) {
            addCriterion("nid not in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidBetween(Integer value1, Integer value2) {
            addCriterion("nid between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotBetween(Integer value1, Integer value2) {
            addCriterion("nid not between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andSetidIsNull() {
            addCriterion("setid is null");
            return (Criteria) this;
        }

        public Criteria andSetidIsNotNull() {
            addCriterion("setid is not null");
            return (Criteria) this;
        }

        public Criteria andSetidEqualTo(Short value) {
            addCriterion("setid =", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidNotEqualTo(Short value) {
            addCriterion("setid <>", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidGreaterThan(Short value) {
            addCriterion("setid >", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidGreaterThanOrEqualTo(Short value) {
            addCriterion("setid >=", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidLessThan(Short value) {
            addCriterion("setid <", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidLessThanOrEqualTo(Short value) {
            addCriterion("setid <=", value, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidIn(List<Short> values) {
            addCriterion("setid in", values, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidNotIn(List<Short> values) {
            addCriterion("setid not in", values, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidBetween(Short value1, Short value2) {
            addCriterion("setid between", value1, value2, "setid");
            return (Criteria) this;
        }

        public Criteria andSetidNotBetween(Short value1, Short value2) {
            addCriterion("setid not between", value1, value2, "setid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNull() {
            addCriterion("checktype is null");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNotNull() {
            addCriterion("checktype is not null");
            return (Criteria) this;
        }

        public Criteria andChecktypeEqualTo(String value) {
            addCriterion("checktype =", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotEqualTo(String value) {
            addCriterion("checktype <>", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThan(String value) {
            addCriterion("checktype >", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThanOrEqualTo(String value) {
            addCriterion("checktype >=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThan(String value) {
            addCriterion("checktype <", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThanOrEqualTo(String value) {
            addCriterion("checktype <=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLike(String value) {
            addCriterion("checktype like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotLike(String value) {
            addCriterion("checktype not like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeIn(List<String> values) {
            addCriterion("checktype in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotIn(List<String> values) {
            addCriterion("checktype not in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeBetween(String value1, String value2) {
            addCriterion("checktype between", value1, value2, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotBetween(String value1, String value2) {
            addCriterion("checktype not between", value1, value2, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeidIsNull() {
            addCriterion("checktypeid is null");
            return (Criteria) this;
        }

        public Criteria andChecktypeidIsNotNull() {
            addCriterion("checktypeid is not null");
            return (Criteria) this;
        }

        public Criteria andChecktypeidEqualTo(String value) {
            addCriterion("checktypeid =", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidNotEqualTo(String value) {
            addCriterion("checktypeid <>", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidGreaterThan(String value) {
            addCriterion("checktypeid >", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidGreaterThanOrEqualTo(String value) {
            addCriterion("checktypeid >=", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidLessThan(String value) {
            addCriterion("checktypeid <", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidLessThanOrEqualTo(String value) {
            addCriterion("checktypeid <=", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidLike(String value) {
            addCriterion("checktypeid like", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidNotLike(String value) {
            addCriterion("checktypeid not like", value, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidIn(List<String> values) {
            addCriterion("checktypeid in", values, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidNotIn(List<String> values) {
            addCriterion("checktypeid not in", values, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidBetween(String value1, String value2) {
            addCriterion("checktypeid between", value1, value2, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypeidNotBetween(String value1, String value2) {
            addCriterion("checktypeid not between", value1, value2, "checktypeid");
            return (Criteria) this;
        }

        public Criteria andChecktypenameIsNull() {
            addCriterion("checktypename is null");
            return (Criteria) this;
        }

        public Criteria andChecktypenameIsNotNull() {
            addCriterion("checktypename is not null");
            return (Criteria) this;
        }

        public Criteria andChecktypenameEqualTo(String value) {
            addCriterion("checktypename =", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameNotEqualTo(String value) {
            addCriterion("checktypename <>", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameGreaterThan(String value) {
            addCriterion("checktypename >", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameGreaterThanOrEqualTo(String value) {
            addCriterion("checktypename >=", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameLessThan(String value) {
            addCriterion("checktypename <", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameLessThanOrEqualTo(String value) {
            addCriterion("checktypename <=", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameLike(String value) {
            addCriterion("checktypename like", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameNotLike(String value) {
            addCriterion("checktypename not like", value, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameIn(List<String> values) {
            addCriterion("checktypename in", values, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameNotIn(List<String> values) {
            addCriterion("checktypename not in", values, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameBetween(String value1, String value2) {
            addCriterion("checktypename between", value1, value2, "checktypename");
            return (Criteria) this;
        }

        public Criteria andChecktypenameNotBetween(String value1, String value2) {
            addCriterion("checktypename not between", value1, value2, "checktypename");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Short value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Short value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Short value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Short value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Short value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Short value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Short> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Short> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Short value1, Short value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Short value1, Short value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andWhereidIsNull() {
            addCriterion("whereid is null");
            return (Criteria) this;
        }

        public Criteria andWhereidIsNotNull() {
            addCriterion("whereid is not null");
            return (Criteria) this;
        }

        public Criteria andWhereidEqualTo(Short value) {
            addCriterion("whereid =", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidNotEqualTo(Short value) {
            addCriterion("whereid <>", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidGreaterThan(Short value) {
            addCriterion("whereid >", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidGreaterThanOrEqualTo(Short value) {
            addCriterion("whereid >=", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidLessThan(Short value) {
            addCriterion("whereid <", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidLessThanOrEqualTo(Short value) {
            addCriterion("whereid <=", value, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidIn(List<Short> values) {
            addCriterion("whereid in", values, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidNotIn(List<Short> values) {
            addCriterion("whereid not in", values, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidBetween(Short value1, Short value2) {
            addCriterion("whereid between", value1, value2, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereidNotBetween(Short value1, Short value2) {
            addCriterion("whereid not between", value1, value2, "whereid");
            return (Criteria) this;
        }

        public Criteria andWhereIsNull() {
            addCriterion("where is null");
            return (Criteria) this;
        }

        public Criteria andWhereIsNotNull() {
            addCriterion("where is not null");
            return (Criteria) this;
        }

        public Criteria andWhereEqualTo(String value) {
            addCriterion("where =", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotEqualTo(String value) {
            addCriterion("where <>", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereGreaterThan(String value) {
            addCriterion("where >", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereGreaterThanOrEqualTo(String value) {
            addCriterion("where >=", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLessThan(String value) {
            addCriterion("where <", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLessThanOrEqualTo(String value) {
            addCriterion("where <=", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLike(String value) {
            addCriterion("where like", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotLike(String value) {
            addCriterion("where not like", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereIn(List<String> values) {
            addCriterion("where in", values, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotIn(List<String> values) {
            addCriterion("where not in", values, "where");
            return (Criteria) this;
        }

        public Criteria andWhereBetween(String value1, String value2) {
            addCriterion("where between", value1, value2, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotBetween(String value1, String value2) {
            addCriterion("where not between", value1, value2, "where");
            return (Criteria) this;
        }

        public Criteria andExplainIsNull() {
            addCriterion("explain is null");
            return (Criteria) this;
        }

        public Criteria andExplainIsNotNull() {
            addCriterion("explain is not null");
            return (Criteria) this;
        }

        public Criteria andExplainEqualTo(String value) {
            addCriterion("explain =", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotEqualTo(String value) {
            addCriterion("explain <>", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainGreaterThan(String value) {
            addCriterion("explain >", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainGreaterThanOrEqualTo(String value) {
            addCriterion("explain >=", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLessThan(String value) {
            addCriterion("explain <", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLessThanOrEqualTo(String value) {
            addCriterion("explain <=", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainLike(String value) {
            addCriterion("explain like", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotLike(String value) {
            addCriterion("explain not like", value, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainIn(List<String> values) {
            addCriterion("explain in", values, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotIn(List<String> values) {
            addCriterion("explain not in", values, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainBetween(String value1, String value2) {
            addCriterion("explain between", value1, value2, "explain");
            return (Criteria) this;
        }

        public Criteria andExplainNotBetween(String value1, String value2) {
            addCriterion("explain not between", value1, value2, "explain");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNull() {
            addCriterion("optdt is null");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNotNull() {
            addCriterion("optdt is not null");
            return (Criteria) this;
        }

        public Criteria andOptdtEqualTo(Date value) {
            addCriterion("optdt =", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotEqualTo(Date value) {
            addCriterion("optdt <>", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThan(Date value) {
            addCriterion("optdt >", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThanOrEqualTo(Date value) {
            addCriterion("optdt >=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThan(Date value) {
            addCriterion("optdt <", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThanOrEqualTo(Date value) {
            addCriterion("optdt <=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtIn(List<Date> values) {
            addCriterion("optdt in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotIn(List<Date> values) {
            addCriterion("optdt not in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtBetween(Date value1, Date value2) {
            addCriterion("optdt between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotBetween(Date value1, Date value2) {
            addCriterion("optdt not between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCourseactIsNull() {
            addCriterion("courseact is null");
            return (Criteria) this;
        }

        public Criteria andCourseactIsNotNull() {
            addCriterion("courseact is not null");
            return (Criteria) this;
        }

        public Criteria andCourseactEqualTo(String value) {
            addCriterion("courseact =", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactNotEqualTo(String value) {
            addCriterion("courseact <>", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactGreaterThan(String value) {
            addCriterion("courseact >", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactGreaterThanOrEqualTo(String value) {
            addCriterion("courseact >=", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactLessThan(String value) {
            addCriterion("courseact <", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactLessThanOrEqualTo(String value) {
            addCriterion("courseact <=", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactLike(String value) {
            addCriterion("courseact like", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactNotLike(String value) {
            addCriterion("courseact not like", value, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactIn(List<String> values) {
            addCriterion("courseact in", values, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactNotIn(List<String> values) {
            addCriterion("courseact not in", values, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactBetween(String value1, String value2) {
            addCriterion("courseact between", value1, value2, "courseact");
            return (Criteria) this;
        }

        public Criteria andCourseactNotBetween(String value1, String value2) {
            addCriterion("courseact not between", value1, value2, "courseact");
            return (Criteria) this;
        }

        public Criteria andCheckshuIsNull() {
            addCriterion("checkshu is null");
            return (Criteria) this;
        }

        public Criteria andCheckshuIsNotNull() {
            addCriterion("checkshu is not null");
            return (Criteria) this;
        }

        public Criteria andCheckshuEqualTo(Byte value) {
            addCriterion("checkshu =", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuNotEqualTo(Byte value) {
            addCriterion("checkshu <>", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuGreaterThan(Byte value) {
            addCriterion("checkshu >", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuGreaterThanOrEqualTo(Byte value) {
            addCriterion("checkshu >=", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuLessThan(Byte value) {
            addCriterion("checkshu <", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuLessThanOrEqualTo(Byte value) {
            addCriterion("checkshu <=", value, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuIn(List<Byte> values) {
            addCriterion("checkshu in", values, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuNotIn(List<Byte> values) {
            addCriterion("checkshu not in", values, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuBetween(Byte value1, Byte value2) {
            addCriterion("checkshu between", value1, value2, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckshuNotBetween(Byte value1, Byte value2) {
            addCriterion("checkshu not between", value1, value2, "checkshu");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsIsNull() {
            addCriterion("checkfields is null");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsIsNotNull() {
            addCriterion("checkfields is not null");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsEqualTo(String value) {
            addCriterion("checkfields =", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsNotEqualTo(String value) {
            addCriterion("checkfields <>", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsGreaterThan(String value) {
            addCriterion("checkfields >", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsGreaterThanOrEqualTo(String value) {
            addCriterion("checkfields >=", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsLessThan(String value) {
            addCriterion("checkfields <", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsLessThanOrEqualTo(String value) {
            addCriterion("checkfields <=", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsLike(String value) {
            addCriterion("checkfields like", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsNotLike(String value) {
            addCriterion("checkfields not like", value, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsIn(List<String> values) {
            addCriterion("checkfields in", values, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsNotIn(List<String> values) {
            addCriterion("checkfields not in", values, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsBetween(String value1, String value2) {
            addCriterion("checkfields between", value1, value2, "checkfields");
            return (Criteria) this;
        }

        public Criteria andCheckfieldsNotBetween(String value1, String value2) {
            addCriterion("checkfields not between", value1, value2, "checkfields");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Short value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Short value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Short value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Short value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Short value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Short value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Short> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Short> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Short value1, Short value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Short value1, Short value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andOptidIsNull() {
            addCriterion("optid is null");
            return (Criteria) this;
        }

        public Criteria andOptidIsNotNull() {
            addCriterion("optid is not null");
            return (Criteria) this;
        }

        public Criteria andOptidEqualTo(Short value) {
            addCriterion("optid =", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotEqualTo(Short value) {
            addCriterion("optid <>", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThan(Short value) {
            addCriterion("optid >", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThanOrEqualTo(Short value) {
            addCriterion("optid >=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThan(Short value) {
            addCriterion("optid <", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThanOrEqualTo(Short value) {
            addCriterion("optid <=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidIn(List<Short> values) {
            addCriterion("optid in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotIn(List<Short> values) {
            addCriterion("optid not in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidBetween(Short value1, Short value2) {
            addCriterion("optid between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotBetween(Short value1, Short value2) {
            addCriterion("optid not between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andOptnameIsNull() {
            addCriterion("optname is null");
            return (Criteria) this;
        }

        public Criteria andOptnameIsNotNull() {
            addCriterion("optname is not null");
            return (Criteria) this;
        }

        public Criteria andOptnameEqualTo(String value) {
            addCriterion("optname =", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotEqualTo(String value) {
            addCriterion("optname <>", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameGreaterThan(String value) {
            addCriterion("optname >", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameGreaterThanOrEqualTo(String value) {
            addCriterion("optname >=", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLessThan(String value) {
            addCriterion("optname <", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLessThanOrEqualTo(String value) {
            addCriterion("optname <=", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLike(String value) {
            addCriterion("optname like", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotLike(String value) {
            addCriterion("optname not like", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameIn(List<String> values) {
            addCriterion("optname in", values, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotIn(List<String> values) {
            addCriterion("optname not in", values, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameBetween(String value1, String value2) {
            addCriterion("optname between", value1, value2, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotBetween(String value1, String value2) {
            addCriterion("optname not between", value1, value2, "optname");
            return (Criteria) this;
        }

        public Criteria andReceidIsNull() {
            addCriterion("receid is null");
            return (Criteria) this;
        }

        public Criteria andReceidIsNotNull() {
            addCriterion("receid is not null");
            return (Criteria) this;
        }

        public Criteria andReceidEqualTo(String value) {
            addCriterion("receid =", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotEqualTo(String value) {
            addCriterion("receid <>", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThan(String value) {
            addCriterion("receid >", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThanOrEqualTo(String value) {
            addCriterion("receid >=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThan(String value) {
            addCriterion("receid <", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThanOrEqualTo(String value) {
            addCriterion("receid <=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLike(String value) {
            addCriterion("receid like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotLike(String value) {
            addCriterion("receid not like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidIn(List<String> values) {
            addCriterion("receid in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotIn(List<String> values) {
            addCriterion("receid not in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidBetween(String value1, String value2) {
            addCriterion("receid between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotBetween(String value1, String value2) {
            addCriterion("receid not between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNull() {
            addCriterion("recename is null");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNotNull() {
            addCriterion("recename is not null");
            return (Criteria) this;
        }

        public Criteria andRecenameEqualTo(String value) {
            addCriterion("recename =", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotEqualTo(String value) {
            addCriterion("recename <>", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThan(String value) {
            addCriterion("recename >", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThanOrEqualTo(String value) {
            addCriterion("recename >=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThan(String value) {
            addCriterion("recename <", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThanOrEqualTo(String value) {
            addCriterion("recename <=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLike(String value) {
            addCriterion("recename like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotLike(String value) {
            addCriterion("recename not like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameIn(List<String> values) {
            addCriterion("recename in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotIn(List<String> values) {
            addCriterion("recename not in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameBetween(String value1, String value2) {
            addCriterion("recename between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotBetween(String value1, String value2) {
            addCriterion("recename not between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andIszfIsNull() {
            addCriterion("iszf is null");
            return (Criteria) this;
        }

        public Criteria andIszfIsNotNull() {
            addCriterion("iszf is not null");
            return (Criteria) this;
        }

        public Criteria andIszfEqualTo(Boolean value) {
            addCriterion("iszf =", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfNotEqualTo(Boolean value) {
            addCriterion("iszf <>", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfGreaterThan(Boolean value) {
            addCriterion("iszf >", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("iszf >=", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfLessThan(Boolean value) {
            addCriterion("iszf <", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfLessThanOrEqualTo(Boolean value) {
            addCriterion("iszf <=", value, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfIn(List<Boolean> values) {
            addCriterion("iszf in", values, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfNotIn(List<Boolean> values) {
            addCriterion("iszf not in", values, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfBetween(Boolean value1, Boolean value2) {
            addCriterion("iszf between", value1, value2, "iszf");
            return (Criteria) this;
        }

        public Criteria andIszfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("iszf not between", value1, value2, "iszf");
            return (Criteria) this;
        }

        public Criteria andIsqmIsNull() {
            addCriterion("isqm is null");
            return (Criteria) this;
        }

        public Criteria andIsqmIsNotNull() {
            addCriterion("isqm is not null");
            return (Criteria) this;
        }

        public Criteria andIsqmEqualTo(Boolean value) {
            addCriterion("isqm =", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmNotEqualTo(Boolean value) {
            addCriterion("isqm <>", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmGreaterThan(Boolean value) {
            addCriterion("isqm >", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isqm >=", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmLessThan(Boolean value) {
            addCriterion("isqm <", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmLessThanOrEqualTo(Boolean value) {
            addCriterion("isqm <=", value, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmIn(List<Boolean> values) {
            addCriterion("isqm in", values, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmNotIn(List<Boolean> values) {
            addCriterion("isqm not in", values, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmBetween(Boolean value1, Boolean value2) {
            addCriterion("isqm between", value1, value2, "isqm");
            return (Criteria) this;
        }

        public Criteria andIsqmNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isqm not between", value1, value2, "isqm");
            return (Criteria) this;
        }

        public Criteria andCoursetypeIsNull() {
            addCriterion("coursetype is null");
            return (Criteria) this;
        }

        public Criteria andCoursetypeIsNotNull() {
            addCriterion("coursetype is not null");
            return (Criteria) this;
        }

        public Criteria andCoursetypeEqualTo(Boolean value) {
            addCriterion("coursetype =", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeNotEqualTo(Boolean value) {
            addCriterion("coursetype <>", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeGreaterThan(Boolean value) {
            addCriterion("coursetype >", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("coursetype >=", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeLessThan(Boolean value) {
            addCriterion("coursetype <", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeLessThanOrEqualTo(Boolean value) {
            addCriterion("coursetype <=", value, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeIn(List<Boolean> values) {
            addCriterion("coursetype in", values, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeNotIn(List<Boolean> values) {
            addCriterion("coursetype not in", values, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeBetween(Boolean value1, Boolean value2) {
            addCriterion("coursetype between", value1, value2, "coursetype");
            return (Criteria) this;
        }

        public Criteria andCoursetypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("coursetype not between", value1, value2, "coursetype");
            return (Criteria) this;
        }

        public Criteria andZshtimeIsNull() {
            addCriterion("zshtime is null");
            return (Criteria) this;
        }

        public Criteria andZshtimeIsNotNull() {
            addCriterion("zshtime is not null");
            return (Criteria) this;
        }

        public Criteria andZshtimeEqualTo(Integer value) {
            addCriterion("zshtime =", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeNotEqualTo(Integer value) {
            addCriterion("zshtime <>", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeGreaterThan(Integer value) {
            addCriterion("zshtime >", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("zshtime >=", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeLessThan(Integer value) {
            addCriterion("zshtime <", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeLessThanOrEqualTo(Integer value) {
            addCriterion("zshtime <=", value, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeIn(List<Integer> values) {
            addCriterion("zshtime in", values, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeNotIn(List<Integer> values) {
            addCriterion("zshtime not in", values, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeBetween(Integer value1, Integer value2) {
            addCriterion("zshtime between", value1, value2, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("zshtime not between", value1, value2, "zshtime");
            return (Criteria) this;
        }

        public Criteria andZshstateIsNull() {
            addCriterion("zshstate is null");
            return (Criteria) this;
        }

        public Criteria andZshstateIsNotNull() {
            addCriterion("zshstate is not null");
            return (Criteria) this;
        }

        public Criteria andZshstateEqualTo(Byte value) {
            addCriterion("zshstate =", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateNotEqualTo(Byte value) {
            addCriterion("zshstate <>", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateGreaterThan(Byte value) {
            addCriterion("zshstate >", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateGreaterThanOrEqualTo(Byte value) {
            addCriterion("zshstate >=", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateLessThan(Byte value) {
            addCriterion("zshstate <", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateLessThanOrEqualTo(Byte value) {
            addCriterion("zshstate <=", value, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateIn(List<Byte> values) {
            addCriterion("zshstate in", values, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateNotIn(List<Byte> values) {
            addCriterion("zshstate not in", values, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateBetween(Byte value1, Byte value2) {
            addCriterion("zshstate between", value1, value2, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZshstateNotBetween(Byte value1, Byte value2) {
            addCriterion("zshstate not between", value1, value2, "zshstate");
            return (Criteria) this;
        }

        public Criteria andZbrangeameIsNull() {
            addCriterion("zbrangeame is null");
            return (Criteria) this;
        }

        public Criteria andZbrangeameIsNotNull() {
            addCriterion("zbrangeame is not null");
            return (Criteria) this;
        }

        public Criteria andZbrangeameEqualTo(String value) {
            addCriterion("zbrangeame =", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameNotEqualTo(String value) {
            addCriterion("zbrangeame <>", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameGreaterThan(String value) {
            addCriterion("zbrangeame >", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameGreaterThanOrEqualTo(String value) {
            addCriterion("zbrangeame >=", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameLessThan(String value) {
            addCriterion("zbrangeame <", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameLessThanOrEqualTo(String value) {
            addCriterion("zbrangeame <=", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameLike(String value) {
            addCriterion("zbrangeame like", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameNotLike(String value) {
            addCriterion("zbrangeame not like", value, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameIn(List<String> values) {
            addCriterion("zbrangeame in", values, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameNotIn(List<String> values) {
            addCriterion("zbrangeame not in", values, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameBetween(String value1, String value2) {
            addCriterion("zbrangeame between", value1, value2, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeameNotBetween(String value1, String value2) {
            addCriterion("zbrangeame not between", value1, value2, "zbrangeame");
            return (Criteria) this;
        }

        public Criteria andZbrangeidIsNull() {
            addCriterion("zbrangeid is null");
            return (Criteria) this;
        }

        public Criteria andZbrangeidIsNotNull() {
            addCriterion("zbrangeid is not null");
            return (Criteria) this;
        }

        public Criteria andZbrangeidEqualTo(String value) {
            addCriterion("zbrangeid =", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidNotEqualTo(String value) {
            addCriterion("zbrangeid <>", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidGreaterThan(String value) {
            addCriterion("zbrangeid >", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidGreaterThanOrEqualTo(String value) {
            addCriterion("zbrangeid >=", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidLessThan(String value) {
            addCriterion("zbrangeid <", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidLessThanOrEqualTo(String value) {
            addCriterion("zbrangeid <=", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidLike(String value) {
            addCriterion("zbrangeid like", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidNotLike(String value) {
            addCriterion("zbrangeid not like", value, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidIn(List<String> values) {
            addCriterion("zbrangeid in", values, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidNotIn(List<String> values) {
            addCriterion("zbrangeid not in", values, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidBetween(String value1, String value2) {
            addCriterion("zbrangeid between", value1, value2, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andZbrangeidNotBetween(String value1, String value2) {
            addCriterion("zbrangeid not between", value1, value2, "zbrangeid");
            return (Criteria) this;
        }

        public Criteria andSmlxIsNull() {
            addCriterion("smlx is null");
            return (Criteria) this;
        }

        public Criteria andSmlxIsNotNull() {
            addCriterion("smlx is not null");
            return (Criteria) this;
        }

        public Criteria andSmlxEqualTo(Boolean value) {
            addCriterion("smlx =", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxNotEqualTo(Boolean value) {
            addCriterion("smlx <>", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxGreaterThan(Boolean value) {
            addCriterion("smlx >", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("smlx >=", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxLessThan(Boolean value) {
            addCriterion("smlx <", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxLessThanOrEqualTo(Boolean value) {
            addCriterion("smlx <=", value, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxIn(List<Boolean> values) {
            addCriterion("smlx in", values, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxNotIn(List<Boolean> values) {
            addCriterion("smlx not in", values, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxBetween(Boolean value1, Boolean value2) {
            addCriterion("smlx between", value1, value2, "smlx");
            return (Criteria) this;
        }

        public Criteria andSmlxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("smlx not between", value1, value2, "smlx");
            return (Criteria) this;
        }

        public Criteria andWjlxIsNull() {
            addCriterion("wjlx is null");
            return (Criteria) this;
        }

        public Criteria andWjlxIsNotNull() {
            addCriterion("wjlx is not null");
            return (Criteria) this;
        }

        public Criteria andWjlxEqualTo(Boolean value) {
            addCriterion("wjlx =", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxNotEqualTo(Boolean value) {
            addCriterion("wjlx <>", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxGreaterThan(Boolean value) {
            addCriterion("wjlx >", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("wjlx >=", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxLessThan(Boolean value) {
            addCriterion("wjlx <", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxLessThanOrEqualTo(Boolean value) {
            addCriterion("wjlx <=", value, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxIn(List<Boolean> values) {
            addCriterion("wjlx in", values, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxNotIn(List<Boolean> values) {
            addCriterion("wjlx not in", values, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxBetween(Boolean value1, Boolean value2) {
            addCriterion("wjlx between", value1, value2, "wjlx");
            return (Criteria) this;
        }

        public Criteria andWjlxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("wjlx not between", value1, value2, "wjlx");
            return (Criteria) this;
        }

        public Criteria andIsxgfjIsNull() {
            addCriterion("isxgfj is null");
            return (Criteria) this;
        }

        public Criteria andIsxgfjIsNotNull() {
            addCriterion("isxgfj is not null");
            return (Criteria) this;
        }

        public Criteria andIsxgfjEqualTo(Boolean value) {
            addCriterion("isxgfj =", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjNotEqualTo(Boolean value) {
            addCriterion("isxgfj <>", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjGreaterThan(Boolean value) {
            addCriterion("isxgfj >", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isxgfj >=", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjLessThan(Boolean value) {
            addCriterion("isxgfj <", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjLessThanOrEqualTo(Boolean value) {
            addCriterion("isxgfj <=", value, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjIn(List<Boolean> values) {
            addCriterion("isxgfj in", values, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjNotIn(List<Boolean> values) {
            addCriterion("isxgfj not in", values, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjBetween(Boolean value1, Boolean value2) {
            addCriterion("isxgfj between", value1, value2, "isxgfj");
            return (Criteria) this;
        }

        public Criteria andIsxgfjNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isxgfj not between", value1, value2, "isxgfj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_flow_course
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}