package com.org.fourfly.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FourflyEmailContExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public FourflyEmailContExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andReceidIsNull() {
            addCriterion("receid is null");
            return (Criteria) this;
        }

        public Criteria andReceidIsNotNull() {
            addCriterion("receid is not null");
            return (Criteria) this;
        }

        public Criteria andReceidEqualTo(String value) {
            addCriterion("receid =", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotEqualTo(String value) {
            addCriterion("receid <>", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThan(String value) {
            addCriterion("receid >", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidGreaterThanOrEqualTo(String value) {
            addCriterion("receid >=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThan(String value) {
            addCriterion("receid <", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLessThanOrEqualTo(String value) {
            addCriterion("receid <=", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidLike(String value) {
            addCriterion("receid like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotLike(String value) {
            addCriterion("receid not like", value, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidIn(List<String> values) {
            addCriterion("receid in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotIn(List<String> values) {
            addCriterion("receid not in", values, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidBetween(String value1, String value2) {
            addCriterion("receid between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andReceidNotBetween(String value1, String value2) {
            addCriterion("receid not between", value1, value2, "receid");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNull() {
            addCriterion("recename is null");
            return (Criteria) this;
        }

        public Criteria andRecenameIsNotNull() {
            addCriterion("recename is not null");
            return (Criteria) this;
        }

        public Criteria andRecenameEqualTo(String value) {
            addCriterion("recename =", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotEqualTo(String value) {
            addCriterion("recename <>", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThan(String value) {
            addCriterion("recename >", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameGreaterThanOrEqualTo(String value) {
            addCriterion("recename >=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThan(String value) {
            addCriterion("recename <", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLessThanOrEqualTo(String value) {
            addCriterion("recename <=", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameLike(String value) {
            addCriterion("recename like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotLike(String value) {
            addCriterion("recename not like", value, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameIn(List<String> values) {
            addCriterion("recename in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotIn(List<String> values) {
            addCriterion("recename not in", values, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameBetween(String value1, String value2) {
            addCriterion("recename between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andRecenameNotBetween(String value1, String value2) {
            addCriterion("recename not between", value1, value2, "recename");
            return (Criteria) this;
        }

        public Criteria andReceemailIsNull() {
            addCriterion("receemail is null");
            return (Criteria) this;
        }

        public Criteria andReceemailIsNotNull() {
            addCriterion("receemail is not null");
            return (Criteria) this;
        }

        public Criteria andReceemailEqualTo(String value) {
            addCriterion("receemail =", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailNotEqualTo(String value) {
            addCriterion("receemail <>", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailGreaterThan(String value) {
            addCriterion("receemail >", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailGreaterThanOrEqualTo(String value) {
            addCriterion("receemail >=", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailLessThan(String value) {
            addCriterion("receemail <", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailLessThanOrEqualTo(String value) {
            addCriterion("receemail <=", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailLike(String value) {
            addCriterion("receemail like", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailNotLike(String value) {
            addCriterion("receemail not like", value, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailIn(List<String> values) {
            addCriterion("receemail in", values, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailNotIn(List<String> values) {
            addCriterion("receemail not in", values, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailBetween(String value1, String value2) {
            addCriterion("receemail between", value1, value2, "receemail");
            return (Criteria) this;
        }

        public Criteria andReceemailNotBetween(String value1, String value2) {
            addCriterion("receemail not between", value1, value2, "receemail");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNull() {
            addCriterion("optdt is null");
            return (Criteria) this;
        }

        public Criteria andOptdtIsNotNull() {
            addCriterion("optdt is not null");
            return (Criteria) this;
        }

        public Criteria andOptdtEqualTo(Date value) {
            addCriterion("optdt =", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotEqualTo(Date value) {
            addCriterion("optdt <>", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThan(Date value) {
            addCriterion("optdt >", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtGreaterThanOrEqualTo(Date value) {
            addCriterion("optdt >=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThan(Date value) {
            addCriterion("optdt <", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtLessThanOrEqualTo(Date value) {
            addCriterion("optdt <=", value, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtIn(List<Date> values) {
            addCriterion("optdt in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotIn(List<Date> values) {
            addCriterion("optdt not in", values, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtBetween(Date value1, Date value2) {
            addCriterion("optdt between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptdtNotBetween(Date value1, Date value2) {
            addCriterion("optdt not between", value1, value2, "optdt");
            return (Criteria) this;
        }

        public Criteria andOptidIsNull() {
            addCriterion("optid is null");
            return (Criteria) this;
        }

        public Criteria andOptidIsNotNull() {
            addCriterion("optid is not null");
            return (Criteria) this;
        }

        public Criteria andOptidEqualTo(Short value) {
            addCriterion("optid =", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotEqualTo(Short value) {
            addCriterion("optid <>", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThan(Short value) {
            addCriterion("optid >", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThanOrEqualTo(Short value) {
            addCriterion("optid >=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThan(Short value) {
            addCriterion("optid <", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThanOrEqualTo(Short value) {
            addCriterion("optid <=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidIn(List<Short> values) {
            addCriterion("optid in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotIn(List<Short> values) {
            addCriterion("optid not in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidBetween(Short value1, Short value2) {
            addCriterion("optid between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotBetween(Short value1, Short value2) {
            addCriterion("optid not between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andOptnameIsNull() {
            addCriterion("optname is null");
            return (Criteria) this;
        }

        public Criteria andOptnameIsNotNull() {
            addCriterion("optname is not null");
            return (Criteria) this;
        }

        public Criteria andOptnameEqualTo(String value) {
            addCriterion("optname =", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotEqualTo(String value) {
            addCriterion("optname <>", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameGreaterThan(String value) {
            addCriterion("optname >", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameGreaterThanOrEqualTo(String value) {
            addCriterion("optname >=", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLessThan(String value) {
            addCriterion("optname <", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLessThanOrEqualTo(String value) {
            addCriterion("optname <=", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameLike(String value) {
            addCriterion("optname like", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotLike(String value) {
            addCriterion("optname not like", value, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameIn(List<String> values) {
            addCriterion("optname in", values, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotIn(List<String> values) {
            addCriterion("optname not in", values, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameBetween(String value1, String value2) {
            addCriterion("optname between", value1, value2, "optname");
            return (Criteria) this;
        }

        public Criteria andOptnameNotBetween(String value1, String value2) {
            addCriterion("optname not between", value1, value2, "optname");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSenddtIsNull() {
            addCriterion("senddt is null");
            return (Criteria) this;
        }

        public Criteria andSenddtIsNotNull() {
            addCriterion("senddt is not null");
            return (Criteria) this;
        }

        public Criteria andSenddtEqualTo(Date value) {
            addCriterion("senddt =", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotEqualTo(Date value) {
            addCriterion("senddt <>", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtGreaterThan(Date value) {
            addCriterion("senddt >", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtGreaterThanOrEqualTo(Date value) {
            addCriterion("senddt >=", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtLessThan(Date value) {
            addCriterion("senddt <", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtLessThanOrEqualTo(Date value) {
            addCriterion("senddt <=", value, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtIn(List<Date> values) {
            addCriterion("senddt in", values, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotIn(List<Date> values) {
            addCriterion("senddt not in", values, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtBetween(Date value1, Date value2) {
            addCriterion("senddt between", value1, value2, "senddt");
            return (Criteria) this;
        }

        public Criteria andSenddtNotBetween(Date value1, Date value2) {
            addCriterion("senddt not between", value1, value2, "senddt");
            return (Criteria) this;
        }

        public Criteria andCcnameIsNull() {
            addCriterion("ccname is null");
            return (Criteria) this;
        }

        public Criteria andCcnameIsNotNull() {
            addCriterion("ccname is not null");
            return (Criteria) this;
        }

        public Criteria andCcnameEqualTo(String value) {
            addCriterion("ccname =", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotEqualTo(String value) {
            addCriterion("ccname <>", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameGreaterThan(String value) {
            addCriterion("ccname >", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameGreaterThanOrEqualTo(String value) {
            addCriterion("ccname >=", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLessThan(String value) {
            addCriterion("ccname <", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLessThanOrEqualTo(String value) {
            addCriterion("ccname <=", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameLike(String value) {
            addCriterion("ccname like", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotLike(String value) {
            addCriterion("ccname not like", value, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameIn(List<String> values) {
            addCriterion("ccname in", values, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotIn(List<String> values) {
            addCriterion("ccname not in", values, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameBetween(String value1, String value2) {
            addCriterion("ccname between", value1, value2, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcnameNotBetween(String value1, String value2) {
            addCriterion("ccname not between", value1, value2, "ccname");
            return (Criteria) this;
        }

        public Criteria andCcemailIsNull() {
            addCriterion("ccemail is null");
            return (Criteria) this;
        }

        public Criteria andCcemailIsNotNull() {
            addCriterion("ccemail is not null");
            return (Criteria) this;
        }

        public Criteria andCcemailEqualTo(String value) {
            addCriterion("ccemail =", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotEqualTo(String value) {
            addCriterion("ccemail <>", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailGreaterThan(String value) {
            addCriterion("ccemail >", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailGreaterThanOrEqualTo(String value) {
            addCriterion("ccemail >=", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLessThan(String value) {
            addCriterion("ccemail <", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLessThanOrEqualTo(String value) {
            addCriterion("ccemail <=", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailLike(String value) {
            addCriterion("ccemail like", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotLike(String value) {
            addCriterion("ccemail not like", value, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailIn(List<String> values) {
            addCriterion("ccemail in", values, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotIn(List<String> values) {
            addCriterion("ccemail not in", values, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailBetween(String value1, String value2) {
            addCriterion("ccemail between", value1, value2, "ccemail");
            return (Criteria) this;
        }

        public Criteria andCcemailNotBetween(String value1, String value2) {
            addCriterion("ccemail not between", value1, value2, "ccemail");
            return (Criteria) this;
        }

        public Criteria andAttachpathIsNull() {
            addCriterion("attachpath is null");
            return (Criteria) this;
        }

        public Criteria andAttachpathIsNotNull() {
            addCriterion("attachpath is not null");
            return (Criteria) this;
        }

        public Criteria andAttachpathEqualTo(String value) {
            addCriterion("attachpath =", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathNotEqualTo(String value) {
            addCriterion("attachpath <>", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathGreaterThan(String value) {
            addCriterion("attachpath >", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathGreaterThanOrEqualTo(String value) {
            addCriterion("attachpath >=", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathLessThan(String value) {
            addCriterion("attachpath <", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathLessThanOrEqualTo(String value) {
            addCriterion("attachpath <=", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathLike(String value) {
            addCriterion("attachpath like", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathNotLike(String value) {
            addCriterion("attachpath not like", value, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathIn(List<String> values) {
            addCriterion("attachpath in", values, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathNotIn(List<String> values) {
            addCriterion("attachpath not in", values, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathBetween(String value1, String value2) {
            addCriterion("attachpath between", value1, value2, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachpathNotBetween(String value1, String value2) {
            addCriterion("attachpath not between", value1, value2, "attachpath");
            return (Criteria) this;
        }

        public Criteria andAttachnameIsNull() {
            addCriterion("attachname is null");
            return (Criteria) this;
        }

        public Criteria andAttachnameIsNotNull() {
            addCriterion("attachname is not null");
            return (Criteria) this;
        }

        public Criteria andAttachnameEqualTo(String value) {
            addCriterion("attachname =", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameNotEqualTo(String value) {
            addCriterion("attachname <>", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameGreaterThan(String value) {
            addCriterion("attachname >", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameGreaterThanOrEqualTo(String value) {
            addCriterion("attachname >=", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameLessThan(String value) {
            addCriterion("attachname <", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameLessThanOrEqualTo(String value) {
            addCriterion("attachname <=", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameLike(String value) {
            addCriterion("attachname like", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameNotLike(String value) {
            addCriterion("attachname not like", value, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameIn(List<String> values) {
            addCriterion("attachname in", values, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameNotIn(List<String> values) {
            addCriterion("attachname not in", values, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameBetween(String value1, String value2) {
            addCriterion("attachname between", value1, value2, "attachname");
            return (Criteria) this;
        }

        public Criteria andAttachnameNotBetween(String value1, String value2) {
            addCriterion("attachname not between", value1, value2, "attachname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fourfly_email_cont
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}