package com.org.fourfly.model;

import java.util.Date;

public class FourflyHrkaohem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.startdt
     *
     * @mbg.generated
     */
    private Date startdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.enddt
     *
     * @mbg.generated
     */
    private Date enddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.receid
     *
     * @mbg.generated
     */
    private String receid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.recename
     *
     * @mbg.generated
     */
    private String recename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.optid
     *
     * @mbg.generated
     */
    private Integer optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.hegfen
     *
     * @mbg.generated
     */
    private Short hegfen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.maxfen
     *
     * @mbg.generated
     */
    private Short maxfen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.pinlv
     *
     * @mbg.generated
     */
    private String pinlv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.sctime
     *
     * @mbg.generated
     */
    private String sctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.pfsj
     *
     * @mbg.generated
     */
    private Short pfsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrkaohem.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.id
     *
     * @return the value of fourfly_hrkaohem.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.id
     *
     * @param id the value for fourfly_hrkaohem.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.title
     *
     * @return the value of fourfly_hrkaohem.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.title
     *
     * @param title the value for fourfly_hrkaohem.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.startdt
     *
     * @return the value of fourfly_hrkaohem.startdt
     *
     * @mbg.generated
     */
    public Date getStartdt() {
        return startdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.startdt
     *
     * @param startdt the value for fourfly_hrkaohem.startdt
     *
     * @mbg.generated
     */
    public void setStartdt(Date startdt) {
        this.startdt = startdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.enddt
     *
     * @return the value of fourfly_hrkaohem.enddt
     *
     * @mbg.generated
     */
    public Date getEnddt() {
        return enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.enddt
     *
     * @param enddt the value for fourfly_hrkaohem.enddt
     *
     * @mbg.generated
     */
    public void setEnddt(Date enddt) {
        this.enddt = enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.receid
     *
     * @return the value of fourfly_hrkaohem.receid
     *
     * @mbg.generated
     */
    public String getReceid() {
        return receid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.receid
     *
     * @param receid the value for fourfly_hrkaohem.receid
     *
     * @mbg.generated
     */
    public void setReceid(String receid) {
        this.receid = receid == null ? null : receid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.recename
     *
     * @return the value of fourfly_hrkaohem.recename
     *
     * @mbg.generated
     */
    public String getRecename() {
        return recename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.recename
     *
     * @param recename the value for fourfly_hrkaohem.recename
     *
     * @mbg.generated
     */
    public void setRecename(String recename) {
        this.recename = recename == null ? null : recename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.optid
     *
     * @return the value of fourfly_hrkaohem.optid
     *
     * @mbg.generated
     */
    public Integer getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.optid
     *
     * @param optid the value for fourfly_hrkaohem.optid
     *
     * @mbg.generated
     */
    public void setOptid(Integer optid) {
        this.optid = optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.optname
     *
     * @return the value of fourfly_hrkaohem.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.optname
     *
     * @param optname the value for fourfly_hrkaohem.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.optdt
     *
     * @return the value of fourfly_hrkaohem.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.optdt
     *
     * @param optdt the value for fourfly_hrkaohem.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.hegfen
     *
     * @return the value of fourfly_hrkaohem.hegfen
     *
     * @mbg.generated
     */
    public Short getHegfen() {
        return hegfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.hegfen
     *
     * @param hegfen the value for fourfly_hrkaohem.hegfen
     *
     * @mbg.generated
     */
    public void setHegfen(Short hegfen) {
        this.hegfen = hegfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.maxfen
     *
     * @return the value of fourfly_hrkaohem.maxfen
     *
     * @mbg.generated
     */
    public Short getMaxfen() {
        return maxfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.maxfen
     *
     * @param maxfen the value for fourfly_hrkaohem.maxfen
     *
     * @mbg.generated
     */
    public void setMaxfen(Short maxfen) {
        this.maxfen = maxfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.pinlv
     *
     * @return the value of fourfly_hrkaohem.pinlv
     *
     * @mbg.generated
     */
    public String getPinlv() {
        return pinlv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.pinlv
     *
     * @param pinlv the value for fourfly_hrkaohem.pinlv
     *
     * @mbg.generated
     */
    public void setPinlv(String pinlv) {
        this.pinlv = pinlv == null ? null : pinlv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.sctime
     *
     * @return the value of fourfly_hrkaohem.sctime
     *
     * @mbg.generated
     */
    public String getSctime() {
        return sctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.sctime
     *
     * @param sctime the value for fourfly_hrkaohem.sctime
     *
     * @mbg.generated
     */
    public void setSctime(String sctime) {
        this.sctime = sctime == null ? null : sctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.pfsj
     *
     * @return the value of fourfly_hrkaohem.pfsj
     *
     * @mbg.generated
     */
    public Short getPfsj() {
        return pfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.pfsj
     *
     * @param pfsj the value for fourfly_hrkaohem.pfsj
     *
     * @mbg.generated
     */
    public void setPfsj(Short pfsj) {
        this.pfsj = pfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.status
     *
     * @return the value of fourfly_hrkaohem.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.status
     *
     * @param status the value for fourfly_hrkaohem.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrkaohem.comid
     *
     * @return the value of fourfly_hrkaohem.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrkaohem.comid
     *
     * @param comid the value for fourfly_hrkaohem.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}