package com.org.fourfly.model;

import java.util.Date;

public class FourflyFlowSet extends FourflyFlowSetKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.table
     *
     * @mbg.generated
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.where
     *
     * @mbg.generated
     */
    private String where;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.summarx
     *
     * @mbg.generated
     */
    private String summarx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.pctx
     *
     * @mbg.generated
     */
    private Boolean pctx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.mctx
     *
     * @mbg.generated
     */
    private Boolean mctx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.wxtx
     *
     * @mbg.generated
     */
    private Boolean wxtx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.emtx
     *
     * @mbg.generated
     */
    private Boolean emtx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.sericnum
     *
     * @mbg.generated
     */
    private String sericnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isflow
     *
     * @mbg.generated
     */
    private Boolean isflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.receid
     *
     * @mbg.generated
     */
    private String receid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.recename
     *
     * @mbg.generated
     */
    private String recename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.islu
     *
     * @mbg.generated
     */
    private Boolean islu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.tables
     *
     * @mbg.generated
     */
    private String tables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.names
     *
     * @mbg.generated
     */
    private String names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.statusstr
     *
     * @mbg.generated
     */
    private String statusstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isgbjl
     *
     * @mbg.generated
     */
    private Boolean isgbjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isgbcy
     *
     * @mbg.generated
     */
    private Boolean isgbcy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isscl
     *
     * @mbg.generated
     */
    private Boolean isscl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isup
     *
     * @mbg.generated
     */
    private Boolean isup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.ddtx
     *
     * @mbg.generated
     */
    private Boolean ddtx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isbxs
     *
     * @mbg.generated
     */
    private Boolean isbxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.lbztxs
     *
     * @mbg.generated
     */
    private Boolean lbztxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.isflowlx
     *
     * @mbg.generated
     */
    private Boolean isflowlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.iscs
     *
     * @mbg.generated
     */
    private Boolean iscs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.zfeitime
     *
     * @mbg.generated
     */
    private Integer zfeitime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.ispl
     *
     * @mbg.generated
     */
    private Boolean ispl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.istxset
     *
     * @mbg.generated
     */
    private Boolean istxset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_set.ishz
     *
     * @mbg.generated
     */
    private Boolean ishz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.name
     *
     * @return the value of fourfly_flow_set.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.name
     *
     * @param name the value for fourfly_flow_set.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.sort
     *
     * @return the value of fourfly_flow_set.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.sort
     *
     * @param sort the value for fourfly_flow_set.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.table
     *
     * @return the value of fourfly_flow_set.table
     *
     * @mbg.generated
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.table
     *
     * @param table the value for fourfly_flow_set.table
     *
     * @mbg.generated
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.where
     *
     * @return the value of fourfly_flow_set.where
     *
     * @mbg.generated
     */
    public String getWhere() {
        return where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.where
     *
     * @param where the value for fourfly_flow_set.where
     *
     * @mbg.generated
     */
    public void setWhere(String where) {
        this.where = where == null ? null : where.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.summary
     *
     * @return the value of fourfly_flow_set.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.summary
     *
     * @param summary the value for fourfly_flow_set.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.summarx
     *
     * @return the value of fourfly_flow_set.summarx
     *
     * @mbg.generated
     */
    public String getSummarx() {
        return summarx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.summarx
     *
     * @param summarx the value for fourfly_flow_set.summarx
     *
     * @mbg.generated
     */
    public void setSummarx(String summarx) {
        this.summarx = summarx == null ? null : summarx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.type
     *
     * @return the value of fourfly_flow_set.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.type
     *
     * @param type the value for fourfly_flow_set.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.pctx
     *
     * @return the value of fourfly_flow_set.pctx
     *
     * @mbg.generated
     */
    public Boolean getPctx() {
        return pctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.pctx
     *
     * @param pctx the value for fourfly_flow_set.pctx
     *
     * @mbg.generated
     */
    public void setPctx(Boolean pctx) {
        this.pctx = pctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.mctx
     *
     * @return the value of fourfly_flow_set.mctx
     *
     * @mbg.generated
     */
    public Boolean getMctx() {
        return mctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.mctx
     *
     * @param mctx the value for fourfly_flow_set.mctx
     *
     * @mbg.generated
     */
    public void setMctx(Boolean mctx) {
        this.mctx = mctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.wxtx
     *
     * @return the value of fourfly_flow_set.wxtx
     *
     * @mbg.generated
     */
    public Boolean getWxtx() {
        return wxtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.wxtx
     *
     * @param wxtx the value for fourfly_flow_set.wxtx
     *
     * @mbg.generated
     */
    public void setWxtx(Boolean wxtx) {
        this.wxtx = wxtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.emtx
     *
     * @return the value of fourfly_flow_set.emtx
     *
     * @mbg.generated
     */
    public Boolean getEmtx() {
        return emtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.emtx
     *
     * @param emtx the value for fourfly_flow_set.emtx
     *
     * @mbg.generated
     */
    public void setEmtx(Boolean emtx) {
        this.emtx = emtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.sericnum
     *
     * @return the value of fourfly_flow_set.sericnum
     *
     * @mbg.generated
     */
    public String getSericnum() {
        return sericnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.sericnum
     *
     * @param sericnum the value for fourfly_flow_set.sericnum
     *
     * @mbg.generated
     */
    public void setSericnum(String sericnum) {
        this.sericnum = sericnum == null ? null : sericnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isflow
     *
     * @return the value of fourfly_flow_set.isflow
     *
     * @mbg.generated
     */
    public Boolean getIsflow() {
        return isflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isflow
     *
     * @param isflow the value for fourfly_flow_set.isflow
     *
     * @mbg.generated
     */
    public void setIsflow(Boolean isflow) {
        this.isflow = isflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.receid
     *
     * @return the value of fourfly_flow_set.receid
     *
     * @mbg.generated
     */
    public String getReceid() {
        return receid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.receid
     *
     * @param receid the value for fourfly_flow_set.receid
     *
     * @mbg.generated
     */
    public void setReceid(String receid) {
        this.receid = receid == null ? null : receid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.recename
     *
     * @return the value of fourfly_flow_set.recename
     *
     * @mbg.generated
     */
    public String getRecename() {
        return recename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.recename
     *
     * @param recename the value for fourfly_flow_set.recename
     *
     * @mbg.generated
     */
    public void setRecename(String recename) {
        this.recename = recename == null ? null : recename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.optdt
     *
     * @return the value of fourfly_flow_set.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.optdt
     *
     * @param optdt the value for fourfly_flow_set.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.status
     *
     * @return the value of fourfly_flow_set.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.status
     *
     * @param status the value for fourfly_flow_set.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.islu
     *
     * @return the value of fourfly_flow_set.islu
     *
     * @mbg.generated
     */
    public Boolean getIslu() {
        return islu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.islu
     *
     * @param islu the value for fourfly_flow_set.islu
     *
     * @mbg.generated
     */
    public void setIslu(Boolean islu) {
        this.islu = islu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.tables
     *
     * @return the value of fourfly_flow_set.tables
     *
     * @mbg.generated
     */
    public String getTables() {
        return tables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.tables
     *
     * @param tables the value for fourfly_flow_set.tables
     *
     * @mbg.generated
     */
    public void setTables(String tables) {
        this.tables = tables == null ? null : tables.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.names
     *
     * @return the value of fourfly_flow_set.names
     *
     * @mbg.generated
     */
    public String getNames() {
        return names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.names
     *
     * @param names the value for fourfly_flow_set.names
     *
     * @mbg.generated
     */
    public void setNames(String names) {
        this.names = names == null ? null : names.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.statusstr
     *
     * @return the value of fourfly_flow_set.statusstr
     *
     * @mbg.generated
     */
    public String getStatusstr() {
        return statusstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.statusstr
     *
     * @param statusstr the value for fourfly_flow_set.statusstr
     *
     * @mbg.generated
     */
    public void setStatusstr(String statusstr) {
        this.statusstr = statusstr == null ? null : statusstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isgbjl
     *
     * @return the value of fourfly_flow_set.isgbjl
     *
     * @mbg.generated
     */
    public Boolean getIsgbjl() {
        return isgbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isgbjl
     *
     * @param isgbjl the value for fourfly_flow_set.isgbjl
     *
     * @mbg.generated
     */
    public void setIsgbjl(Boolean isgbjl) {
        this.isgbjl = isgbjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isgbcy
     *
     * @return the value of fourfly_flow_set.isgbcy
     *
     * @mbg.generated
     */
    public Boolean getIsgbcy() {
        return isgbcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isgbcy
     *
     * @param isgbcy the value for fourfly_flow_set.isgbcy
     *
     * @mbg.generated
     */
    public void setIsgbcy(Boolean isgbcy) {
        this.isgbcy = isgbcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isscl
     *
     * @return the value of fourfly_flow_set.isscl
     *
     * @mbg.generated
     */
    public Boolean getIsscl() {
        return isscl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isscl
     *
     * @param isscl the value for fourfly_flow_set.isscl
     *
     * @mbg.generated
     */
    public void setIsscl(Boolean isscl) {
        this.isscl = isscl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isup
     *
     * @return the value of fourfly_flow_set.isup
     *
     * @mbg.generated
     */
    public Boolean getIsup() {
        return isup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isup
     *
     * @param isup the value for fourfly_flow_set.isup
     *
     * @mbg.generated
     */
    public void setIsup(Boolean isup) {
        this.isup = isup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.ddtx
     *
     * @return the value of fourfly_flow_set.ddtx
     *
     * @mbg.generated
     */
    public Boolean getDdtx() {
        return ddtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.ddtx
     *
     * @param ddtx the value for fourfly_flow_set.ddtx
     *
     * @mbg.generated
     */
    public void setDdtx(Boolean ddtx) {
        this.ddtx = ddtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isbxs
     *
     * @return the value of fourfly_flow_set.isbxs
     *
     * @mbg.generated
     */
    public Boolean getIsbxs() {
        return isbxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isbxs
     *
     * @param isbxs the value for fourfly_flow_set.isbxs
     *
     * @mbg.generated
     */
    public void setIsbxs(Boolean isbxs) {
        this.isbxs = isbxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.lbztxs
     *
     * @return the value of fourfly_flow_set.lbztxs
     *
     * @mbg.generated
     */
    public Boolean getLbztxs() {
        return lbztxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.lbztxs
     *
     * @param lbztxs the value for fourfly_flow_set.lbztxs
     *
     * @mbg.generated
     */
    public void setLbztxs(Boolean lbztxs) {
        this.lbztxs = lbztxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.isflowlx
     *
     * @return the value of fourfly_flow_set.isflowlx
     *
     * @mbg.generated
     */
    public Boolean getIsflowlx() {
        return isflowlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.isflowlx
     *
     * @param isflowlx the value for fourfly_flow_set.isflowlx
     *
     * @mbg.generated
     */
    public void setIsflowlx(Boolean isflowlx) {
        this.isflowlx = isflowlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.iscs
     *
     * @return the value of fourfly_flow_set.iscs
     *
     * @mbg.generated
     */
    public Boolean getIscs() {
        return iscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.iscs
     *
     * @param iscs the value for fourfly_flow_set.iscs
     *
     * @mbg.generated
     */
    public void setIscs(Boolean iscs) {
        this.iscs = iscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.zfeitime
     *
     * @return the value of fourfly_flow_set.zfeitime
     *
     * @mbg.generated
     */
    public Integer getZfeitime() {
        return zfeitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.zfeitime
     *
     * @param zfeitime the value for fourfly_flow_set.zfeitime
     *
     * @mbg.generated
     */
    public void setZfeitime(Integer zfeitime) {
        this.zfeitime = zfeitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.ispl
     *
     * @return the value of fourfly_flow_set.ispl
     *
     * @mbg.generated
     */
    public Boolean getIspl() {
        return ispl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.ispl
     *
     * @param ispl the value for fourfly_flow_set.ispl
     *
     * @mbg.generated
     */
    public void setIspl(Boolean ispl) {
        this.ispl = ispl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.istxset
     *
     * @return the value of fourfly_flow_set.istxset
     *
     * @mbg.generated
     */
    public Boolean getIstxset() {
        return istxset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.istxset
     *
     * @param istxset the value for fourfly_flow_set.istxset
     *
     * @mbg.generated
     */
    public void setIstxset(Boolean istxset) {
        this.istxset = istxset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_set.ishz
     *
     * @return the value of fourfly_flow_set.ishz
     *
     * @mbg.generated
     */
    public Boolean getIshz() {
        return ishz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_set.ishz
     *
     * @param ishz the value for fourfly_flow_set.ishz
     *
     * @mbg.generated
     */
    public void setIshz(Boolean ishz) {
        this.ishz = ishz;
    }
}