package com.org.fourfly.model;

public class FourflyHrsalars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.mid
     *
     * @mbg.generated
     */
    private Short mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.fields
     *
     * @mbg.generated
     */
    private String fields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.gongsi
     *
     * @mbg.generated
     */
    private String gongsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.beizhu
     *
     * @mbg.generated
     */
    private String beizhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.devzhi
     *
     * @mbg.generated
     */
    private String devzhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_hrsalars.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.id
     *
     * @return the value of fourfly_hrsalars.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.id
     *
     * @param id the value for fourfly_hrsalars.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.mid
     *
     * @return the value of fourfly_hrsalars.mid
     *
     * @mbg.generated
     */
    public Short getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.mid
     *
     * @param mid the value for fourfly_hrsalars.mid
     *
     * @mbg.generated
     */
    public void setMid(Short mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.sort
     *
     * @return the value of fourfly_hrsalars.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.sort
     *
     * @param sort the value for fourfly_hrsalars.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.name
     *
     * @return the value of fourfly_hrsalars.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.name
     *
     * @param name the value for fourfly_hrsalars.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.fields
     *
     * @return the value of fourfly_hrsalars.fields
     *
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.fields
     *
     * @param fields the value for fourfly_hrsalars.fields
     *
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.gongsi
     *
     * @return the value of fourfly_hrsalars.gongsi
     *
     * @mbg.generated
     */
    public String getGongsi() {
        return gongsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.gongsi
     *
     * @param gongsi the value for fourfly_hrsalars.gongsi
     *
     * @mbg.generated
     */
    public void setGongsi(String gongsi) {
        this.gongsi = gongsi == null ? null : gongsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.type
     *
     * @return the value of fourfly_hrsalars.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.type
     *
     * @param type the value for fourfly_hrsalars.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.beizhu
     *
     * @return the value of fourfly_hrsalars.beizhu
     *
     * @mbg.generated
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.beizhu
     *
     * @param beizhu the value for fourfly_hrsalars.beizhu
     *
     * @mbg.generated
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.devzhi
     *
     * @return the value of fourfly_hrsalars.devzhi
     *
     * @mbg.generated
     */
    public String getDevzhi() {
        return devzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.devzhi
     *
     * @param devzhi the value for fourfly_hrsalars.devzhi
     *
     * @mbg.generated
     */
    public void setDevzhi(String devzhi) {
        this.devzhi = devzhi == null ? null : devzhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_hrsalars.comid
     *
     * @return the value of fourfly_hrsalars.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_hrsalars.comid
     *
     * @param comid the value for fourfly_hrsalars.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}