package com.org.fourfly.model;

import java.math.BigDecimal;
import java.util.Date;

public class FourflyBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.typeid
     *
     * @mbg.generated
     */
    private Short typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.chuban
     *
     * @mbg.generated
     */
    private String chuban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.cbdt
     *
     * @mbg.generated
     */
    private Date cbdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.weizhi
     *
     * @mbg.generated
     */
    private String weizhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.shul
     *
     * @mbg.generated
     */
    private Short shul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.adddt
     *
     * @mbg.generated
     */
    private Date adddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.optid
     *
     * @mbg.generated
     */
    private Short optid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.isbn
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.jieshu
     *
     * @mbg.generated
     */
    private Short jieshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_book.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.id
     *
     * @return the value of fourfly_book.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.id
     *
     * @param id the value for fourfly_book.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.title
     *
     * @return the value of fourfly_book.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.title
     *
     * @param title the value for fourfly_book.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.typeid
     *
     * @return the value of fourfly_book.typeid
     *
     * @mbg.generated
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.typeid
     *
     * @param typeid the value for fourfly_book.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.num
     *
     * @return the value of fourfly_book.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.num
     *
     * @param num the value for fourfly_book.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.author
     *
     * @return the value of fourfly_book.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.author
     *
     * @param author the value for fourfly_book.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.chuban
     *
     * @return the value of fourfly_book.chuban
     *
     * @mbg.generated
     */
    public String getChuban() {
        return chuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.chuban
     *
     * @param chuban the value for fourfly_book.chuban
     *
     * @mbg.generated
     */
    public void setChuban(String chuban) {
        this.chuban = chuban == null ? null : chuban.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.cbdt
     *
     * @return the value of fourfly_book.cbdt
     *
     * @mbg.generated
     */
    public Date getCbdt() {
        return cbdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.cbdt
     *
     * @param cbdt the value for fourfly_book.cbdt
     *
     * @mbg.generated
     */
    public void setCbdt(Date cbdt) {
        this.cbdt = cbdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.price
     *
     * @return the value of fourfly_book.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.price
     *
     * @param price the value for fourfly_book.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.weizhi
     *
     * @return the value of fourfly_book.weizhi
     *
     * @mbg.generated
     */
    public String getWeizhi() {
        return weizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.weizhi
     *
     * @param weizhi the value for fourfly_book.weizhi
     *
     * @mbg.generated
     */
    public void setWeizhi(String weizhi) {
        this.weizhi = weizhi == null ? null : weizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.shul
     *
     * @return the value of fourfly_book.shul
     *
     * @mbg.generated
     */
    public Short getShul() {
        return shul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.shul
     *
     * @param shul the value for fourfly_book.shul
     *
     * @mbg.generated
     */
    public void setShul(Short shul) {
        this.shul = shul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.adddt
     *
     * @return the value of fourfly_book.adddt
     *
     * @mbg.generated
     */
    public Date getAdddt() {
        return adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.adddt
     *
     * @param adddt the value for fourfly_book.adddt
     *
     * @mbg.generated
     */
    public void setAdddt(Date adddt) {
        this.adddt = adddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.optdt
     *
     * @return the value of fourfly_book.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.optdt
     *
     * @param optdt the value for fourfly_book.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.optname
     *
     * @return the value of fourfly_book.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.optname
     *
     * @param optname the value for fourfly_book.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.optid
     *
     * @return the value of fourfly_book.optid
     *
     * @mbg.generated
     */
    public Short getOptid() {
        return optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.optid
     *
     * @param optid the value for fourfly_book.optid
     *
     * @mbg.generated
     */
    public void setOptid(Short optid) {
        this.optid = optid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.explain
     *
     * @return the value of fourfly_book.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.explain
     *
     * @param explain the value for fourfly_book.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.isbn
     *
     * @return the value of fourfly_book.isbn
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.isbn
     *
     * @param isbn the value for fourfly_book.isbn
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.jieshu
     *
     * @return the value of fourfly_book.jieshu
     *
     * @mbg.generated
     */
    public Short getJieshu() {
        return jieshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.jieshu
     *
     * @param jieshu the value for fourfly_book.jieshu
     *
     * @mbg.generated
     */
    public void setJieshu(Short jieshu) {
        this.jieshu = jieshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_book.comid
     *
     * @return the value of fourfly_book.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_book.comid
     *
     * @param comid the value for fourfly_book.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}