package com.org.fourfly.model;

import java.util.Date;

public class FourflyFlowRemind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.startdt
     *
     * @mbg.generated
     */
    private Date startdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.enddt
     *
     * @mbg.generated
     */
    private Date enddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.uid
     *
     * @mbg.generated
     */
    private Short uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.optdt
     *
     * @mbg.generated
     */
    private Date optdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.optname
     *
     * @mbg.generated
     */
    private String optname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.modenum
     *
     * @mbg.generated
     */
    private String modenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.table
     *
     * @mbg.generated
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.ratecont
     *
     * @mbg.generated
     */
    private String ratecont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.rate
     *
     * @mbg.generated
     */
    private String rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.rateval
     *
     * @mbg.generated
     */
    private String rateval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.receid
     *
     * @mbg.generated
     */
    private String receid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.recename
     *
     * @mbg.generated
     */
    private String recename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fourfly_flow_remind.comid
     *
     * @mbg.generated
     */
    private Short comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.id
     *
     * @return the value of fourfly_flow_remind.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.id
     *
     * @param id the value for fourfly_flow_remind.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.startdt
     *
     * @return the value of fourfly_flow_remind.startdt
     *
     * @mbg.generated
     */
    public Date getStartdt() {
        return startdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.startdt
     *
     * @param startdt the value for fourfly_flow_remind.startdt
     *
     * @mbg.generated
     */
    public void setStartdt(Date startdt) {
        this.startdt = startdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.enddt
     *
     * @return the value of fourfly_flow_remind.enddt
     *
     * @mbg.generated
     */
    public Date getEnddt() {
        return enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.enddt
     *
     * @param enddt the value for fourfly_flow_remind.enddt
     *
     * @mbg.generated
     */
    public void setEnddt(Date enddt) {
        this.enddt = enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.uid
     *
     * @return the value of fourfly_flow_remind.uid
     *
     * @mbg.generated
     */
    public Short getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.uid
     *
     * @param uid the value for fourfly_flow_remind.uid
     *
     * @mbg.generated
     */
    public void setUid(Short uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.optdt
     *
     * @return the value of fourfly_flow_remind.optdt
     *
     * @mbg.generated
     */
    public Date getOptdt() {
        return optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.optdt
     *
     * @param optdt the value for fourfly_flow_remind.optdt
     *
     * @mbg.generated
     */
    public void setOptdt(Date optdt) {
        this.optdt = optdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.optname
     *
     * @return the value of fourfly_flow_remind.optname
     *
     * @mbg.generated
     */
    public String getOptname() {
        return optname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.optname
     *
     * @param optname the value for fourfly_flow_remind.optname
     *
     * @mbg.generated
     */
    public void setOptname(String optname) {
        this.optname = optname == null ? null : optname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.modenum
     *
     * @return the value of fourfly_flow_remind.modenum
     *
     * @mbg.generated
     */
    public String getModenum() {
        return modenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.modenum
     *
     * @param modenum the value for fourfly_flow_remind.modenum
     *
     * @mbg.generated
     */
    public void setModenum(String modenum) {
        this.modenum = modenum == null ? null : modenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.table
     *
     * @return the value of fourfly_flow_remind.table
     *
     * @mbg.generated
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.table
     *
     * @param table the value for fourfly_flow_remind.table
     *
     * @mbg.generated
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.mid
     *
     * @return the value of fourfly_flow_remind.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.mid
     *
     * @param mid the value for fourfly_flow_remind.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.ratecont
     *
     * @return the value of fourfly_flow_remind.ratecont
     *
     * @mbg.generated
     */
    public String getRatecont() {
        return ratecont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.ratecont
     *
     * @param ratecont the value for fourfly_flow_remind.ratecont
     *
     * @mbg.generated
     */
    public void setRatecont(String ratecont) {
        this.ratecont = ratecont == null ? null : ratecont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.explain
     *
     * @return the value of fourfly_flow_remind.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.explain
     *
     * @param explain the value for fourfly_flow_remind.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.rate
     *
     * @return the value of fourfly_flow_remind.rate
     *
     * @mbg.generated
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.rate
     *
     * @param rate the value for fourfly_flow_remind.rate
     *
     * @mbg.generated
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.rateval
     *
     * @return the value of fourfly_flow_remind.rateval
     *
     * @mbg.generated
     */
    public String getRateval() {
        return rateval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.rateval
     *
     * @param rateval the value for fourfly_flow_remind.rateval
     *
     * @mbg.generated
     */
    public void setRateval(String rateval) {
        this.rateval = rateval == null ? null : rateval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.status
     *
     * @return the value of fourfly_flow_remind.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.status
     *
     * @param status the value for fourfly_flow_remind.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.receid
     *
     * @return the value of fourfly_flow_remind.receid
     *
     * @mbg.generated
     */
    public String getReceid() {
        return receid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.receid
     *
     * @param receid the value for fourfly_flow_remind.receid
     *
     * @mbg.generated
     */
    public void setReceid(String receid) {
        this.receid = receid == null ? null : receid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.recename
     *
     * @return the value of fourfly_flow_remind.recename
     *
     * @mbg.generated
     */
    public String getRecename() {
        return recename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.recename
     *
     * @param recename the value for fourfly_flow_remind.recename
     *
     * @mbg.generated
     */
    public void setRecename(String recename) {
        this.recename = recename == null ? null : recename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fourfly_flow_remind.comid
     *
     * @return the value of fourfly_flow_remind.comid
     *
     * @mbg.generated
     */
    public Short getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fourfly_flow_remind.comid
     *
     * @param comid the value for fourfly_flow_remind.comid
     *
     * @mbg.generated
     */
    public void setComid(Short comid) {
        this.comid = comid;
    }
}